class FireRunner {
	public static void main(String... values) {
		Fire fire1 = new Fire();
		Fire fire2 = new Fire();
		Fire fire3 = new Fire();
		Fire fire4 = new Fire();
		Fire fire5 = new Fire();
		Fire fire6 = new Fire();
		Fire fire7 = new Fire();
		Fire fire8 = new Fire();
		Fire fire9 = new Fire();
		Fire fire10 = new Fire();

		fire1.type = "Wildfire";
		fire1.intensity = "High";
		fire1.source = "Lightning";
		fire1.spreadRate = "Fast";
		fire1.temperature = "1200C";
		fire1.smoke = "Black";
		fire1.extinguisher = "Water";
		fire1.location = "Forest";
		fire1.cause = "Natural";
		fire1.status = "Active";

		System.out.println("this is fire1 instance:length " + fire1.length);
		System.out.println("this is fire1 instance:width " + fire1.width);
		System.out.println("this is fire1 instance:height " + fire1.height);
		System.out.println("this is fire1 instance:color " + fire1.color);
		System.out.println("this is fire1 instance:material " + fire1.material);
		System.out.println("this is fire1 instance:type " + fire1.type);
		System.out.println("this is fire1 instance:intensity " + fire1.intensity);
		System.out.println("this is fire1 instance:source " + fire1.source);
		System.out.println("this is fire1 instance:spreadRate " + fire1.spreadRate);
		System.out.println("this is fire1 instance:temperature " + fire1.temperature);
		System.out.println("this is fire1 instance:smoke " + fire1.smoke);
		System.out.println("this is fire1 instance:extinguisher " + fire1.extinguisher);
		System.out.println("this is fire1 instance:location " + fire1.location);
		System.out.println("this is fire1 instance:cause " + fire1.cause);
		System.out.println("this is fire1 instance:status " + fire1.status);

		fire2.type = "Campfire";
		fire2.intensity = "Low";
		fire2.source = "Match";
		fire2.spreadRate = "Slow";
		fire2.temperature = "300C";
		fire2.smoke = "White";
		fire2.extinguisher = "Sand";
		fire2.location = "Campsite";
		fire2.cause = "Human";
		fire2.status = "Controlled";

		System.out.println("this is fire2 instance:length " + fire2.length);
		System.out.println("this is fire2 instance:width " + fire2.width);
		System.out.println("this is fire2 instance:height " + fire2.height);
		System.out.println("this is fire2 instance:color " + fire2.color);
		System.out.println("this is fire2 instance:material " + fire2.material);
		System.out.println("this is fire2 instance:type " + fire2.type);
		System.out.println("this is fire2 instance:intensity " + fire2.intensity);
		System.out.println("this is fire2 instance:source " + fire2.source);
		System.out.println("this is fire2 instance:spreadRate " + fire2.spreadRate);
		System.out.println("this is fire2 instance:temperature " + fire2.temperature);
		System.out.println("this is fire2 instance:smoke " + fire2.smoke);
		System.out.println("this is fire2 instance:extinguisher " + fire2.extinguisher);
		System.out.println("this is fire2 instance:location " + fire2.location);
		System.out.println("this is fire2 instance:cause " + fire2.cause);
		System.out.println("this is fire2 instance:status " + fire2.status);

		fire3.type = "Industrial";
		fire3.intensity = "Extreme";
		fire3.source = "Chemical";
		fire3.spreadRate = "VeryFast";
		fire3.temperature = "2000C";
		fire3.smoke = "Grey";
		fire3.extinguisher = "CO2";
		fire3.location = "Factory";
		fire3.cause = "Accident";
		fire3.status = "Active";

		System.out.println("this is fire3 instance:length " + fire3.length);
		System.out.println("this is fire3 instance:width " + fire3.width);
		System.out.println("this is fire3 instance:height " + fire3.height);
		System.out.println("this is fire3 instance:color " + fire3.color);
		System.out.println("this is fire3 instance:material " + fire3.material);
		System.out.println("this is fire3 instance:type " + fire3.type);
		System.out.println("this is fire3 instance:intensity " + fire3.intensity);
		System.out.println("this is fire3 instance:source " + fire3.source);
		System.out.println("this is fire3 instance:spreadRate " + fire3.spreadRate);
		System.out.println("this is fire3 instance:temperature " + fire3.temperature);
		System.out.println("this is fire3 instance:smoke " + fire3.smoke);
		System.out.println("this is fire3 instance:extinguisher " + fire3.extinguisher);
		System.out.println("this is fire3 instance:location " + fire3.location);
		System.out.println("this is fire3 instance:cause " + fire3.cause);
		System.out.println("this is fire3 instance:status " + fire3.status);

		fire4.type = "Electrical";
		fire4.intensity = "Medium";
		fire4.source = "ShortCircuit";
		fire4.spreadRate = "Medium";
		fire4.temperature = "800C";
		fire4.smoke = "Black";
		fire4.extinguisher = "DryPowder";
		fire4.location = "Office";
		fire4.cause = "Electrical";
		fire4.status = "Extinguished";

		System.out.println("this is fire4 instance:length " + fire4.length);
		System.out.println("this is fire4 instance:width " + fire4.width);
		System.out.println("this is fire4 instance:height " + fire4.height);
		System.out.println("this is fire4 instance:color " + fire4.color);
		System.out.println("this is fire4 instance:material " + fire4.material);
		System.out.println("this is fire4 instance:type " + fire4.type);
		System.out.println("this is fire4 instance:intensity " + fire4.intensity);
		System.out.println("this is fire4 instance:source " + fire4.source);
		System.out.println("this is fire4 instance:spreadRate " + fire4.spreadRate);
		System.out.println("this is fire4 instance:temperature " + fire4.temperature);
		System.out.println("this is fire4 instance:smoke " + fire4.smoke);
		System.out.println("this is fire4 instance:extinguisher " + fire4.extinguisher);
		System.out.println("this is fire4 instance:location " + fire4.location);
		System.out.println("this is fire4 instance:cause " + fire4.cause);
		System.out.println("this is fire4 instance:status " + fire4.status);

		fire5.type = "Grease";
		fire5.intensity = "High";
		fire5.source = "Cooking";
		fire5.spreadRate = "Fast";
		fire5.temperature = "400C";
		fire5.smoke = "Yellow";
		fire5.extinguisher = "FoamSpray";
		fire5.location = "Kitchen";
		fire5.cause = "Negligence";
		fire5.status = "Active";

		System.out.println("this is fire5 instance:length " + fire5.length);
		System.out.println("this is fire5 instance:width " + fire5.width);
		System.out.println("this is fire5 instance:height " + fire5.height);
		System.out.println("this is fire5 instance:color " + fire5.color);
		System.out.println("this is fire5 instance:material " + fire5.material);
		System.out.println("this is fire5 instance:type " + fire5.type);
		System.out.println("this is fire5 instance:intensity " + fire5.intensity);
		System.out.println("this is fire5 instance:source " + fire5.source);
		System.out.println("this is fire5 instance:spreadRate " + fire5.spreadRate);
		System.out.println("this is fire5 instance:temperature " + fire5.temperature);
		System.out.println("this is fire5 instance:smoke " + fire5.smoke);
		System.out.println("this is fire5 instance:extinguisher " + fire5.extinguisher);
		System.out.println("this is fire5 instance:location " + fire5.location);
		System.out.println("this is fire5 instance:cause " + fire5.cause);
		System.out.println("this is fire5 instance:status " + fire5.status);

		fire6.type = "Grassfire";
		fire6.intensity = "Medium";
		fire6.source = "Sunlight";
		fire6.spreadRate = "Medium";
		fire6.temperature = "600C";
		fire6.smoke = "White";
		fire6.extinguisher = "Water";
		fire6.location = "Field";
		fire6.cause = "Natural";
		fire6.status = "Active";

		System.out.println("this is fire6 instance:length " + fire6.length);
		System.out.println("this is fire6 instance:width " + fire6.width);
		System.out.println("this is fire6 instance:height " + fire6.height);
		System.out.println("this is fire6 instance:color " + fire6.color);
		System.out.println("this is fire6 instance:material " + fire6.material);
		System.out.println("this is fire6 instance:type " + fire6.type);
		System.out.println("this is fire6 instance:intensity " + fire6.intensity);
		System.out.println("this is fire6 instance:source " + fire6.source);
		System.out.println("this is fire6 instance:spreadRate " + fire6.spreadRate);
		System.out.println("this is fire6 instance:temperature " + fire6.temperature);
		System.out.println("this is fire6 instance:smoke " + fire6.smoke);
		System.out.println("this is fire6 instance:extinguisher " + fire6.extinguisher);
		System.out.println("this is fire6 instance:location " + fire6.location);
		System.out.println("this is fire6 instance:cause " + fire6.cause);
		System.out.println("this is fire6 instance:status " + fire6.status);

		fire7.type = "Structural";
		fire7.intensity = "Extreme";
		fire7.source = "Gas";
		fire7.spreadRate = "Fast";
		fire7.temperature = "1500C";
		fire7.smoke = "Black";
		fire7.extinguisher = "CO2";
		fire7.location = "Building";
		fire7.cause = "GasLeak";
		fire7.status = "Active";

		System.out.println("this is fire7 instance:length " + fire7.length);
		System.out.println("this is fire7 instance:width " + fire7.width);
		System.out.println("this is fire7 instance:height " + fire7.height);
		System.out.println("this is fire7 instance:color " + fire7.color);
		System.out.println("this is fire7 instance:material " + fire7.material);
		System.out.println("this is fire7 instance:type " + fire7.type);
		System.out.println("this is fire7 instance:intensity " + fire7.intensity);
		System.out.println("this is fire7 instance:source " + fire7.source);
		System.out.println("this is fire7 instance:spreadRate " + fire7.spreadRate);
		System.out.println("this is fire7 instance:temperature " + fire7.temperature);
		System.out.println("this is fire7 instance:smoke " + fire7.smoke);
		System.out.println("this is fire7 instance:extinguisher " + fire7.extinguisher);
		System.out.println("this is fire7 instance:location " + fire7.location);
		System.out.println("this is fire7 instance:cause " + fire7.cause);
		System.out.println("this is fire7 instance:status " + fire7.status);

		fire8.type = "Vehicle";
		fire8.intensity = "High";
		fire8.source = "FuelLeak";
		fire8.spreadRate = "Fast";
		fire8.temperature = "900C";
		fire8.smoke = "Grey";
		fire8.extinguisher = "FoamSpray";
		fire8.location = "Highway";
		fire8.cause = "Accident";
		fire8.status = "Extinguished";

		System.out.println("this is fire8 instance:length " + fire8.length);
		System.out.println("this is fire8 instance:width " + fire8.width);
		System.out.println("this is fire8 instance:height " + fire8.height);
		System.out.println("this is fire8 instance:color " + fire8.color);
		System.out.println("this is fire8 instance:material " + fire8.material);
		System.out.println("this is fire8 instance:type " + fire8.type);
		System.out.println("this is fire8 instance:intensity " + fire8.intensity);
		System.out.println("this is fire8 instance:source " + fire8.source);
		System.out.println("this is fire8 instance:spreadRate " + fire8.spreadRate);
		System.out.println("this is fire8 instance:temperature " + fire8.temperature);
		System.out.println("this is fire8 instance:smoke " + fire8.smoke);
		System.out.println("this is fire8 instance:extinguisher " + fire8.extinguisher);
		System.out.println("this is fire8 instance:location " + fire8.location);
		System.out.println("this is fire8 instance:cause " + fire8.cause);
		System.out.println("this is fire8 instance:status " + fire8.status);

		fire9.type = "Underground";
		fire9.intensity = "Low";
		fire9.source = "Coal";
		fire9.spreadRate = "VerySlow";
		fire9.temperature = "500C";
		fire9.smoke = "Brown";
		fire9.extinguisher = "Sand";
		fire9.location = "Mine";
		fire9.cause = "SpontaneousCombustion";
		fire9.status = "Active";

		System.out.println("this is fire9 instance:length " + fire9.length);
		System.out.println("this is fire9 instance:width " + fire9.width);
		System.out.println("this is fire9 instance:height " + fire9.height);
		System.out.println("this is fire9 instance:color " + fire9.color);
		System.out.println("this is fire9 instance:material " + fire9.material);
		System.out.println("this is fire9 instance:type " + fire9.type);
		System.out.println("this is fire9 instance:intensity " + fire9.intensity);
		System.out.println("this is fire9 instance:source " + fire9.source);
		System.out.println("this is fire9 instance:spreadRate " + fire9.spreadRate);
		System.out.println("this is fire9 instance:temperature " + fire9.temperature);
		System.out.println("this is fire9 instance:smoke " + fire9.smoke);
		System.out.println("this is fire9 instance:extinguisher " + fire9.extinguisher);
		System.out.println("this is fire9 instance:location " + fire9.location);
		System.out.println("this is fire9 instance:cause " + fire9.cause);
		System.out.println("this is fire9 instance:status " + fire9.status);

		fire10.type = "Peatfire";
		fire10.intensity = "Medium";
		fire10.source = "Drought";
		fire10.spreadRate = "Slow";
		fire10.temperature = "700C";
		fire10.smoke = "White";
		fire10.extinguisher = "Water";
		fire10.location = "Wetland";
		fire10.cause = "Natural";
		fire10.status = "Active";

		System.out.println("this is fire10 instance:length " + fire10.length);
		System.out.println("this is fire10 instance:width " + fire10.width);
		System.out.println("this is fire10 instance:height " + fire10.height);
		System.out.println("this is fire10 instance:color " + fire10.color);
		System.out.println("this is fire10 instance:material " + fire10.material);
		System.out.println("this is fire10 instance:type " + fire10.type);
		System.out.println("this is fire10 instance:intensity " + fire10.intensity);
		System.out.println("this is fire10 instance:source " + fire10.source);
		System.out.println("this is fire10 instance:spreadRate " + fire10.spreadRate);
		System.out.println("this is fire10 instance:temperature " + fire10.temperature);
		System.out.println("this is fire10 instance:smoke " + fire10.smoke);
		System.out.println("this is fire10 instance:extinguisher " + fire10.extinguisher);
		System.out.println("this is fire10 instance:location " + fire10.location);
		System.out.println("this is fire10 instance:cause " + fire10.cause);
		System.out.println("this is fire10 instance:status " + fire10.status);

		fire6 = fire7;
		System.out.println("this is fire6 instance:length " + fire6.length);
		System.out.println("this is fire6 instance:width " + fire6.width);
		System.out.println("this is fire6 instance:height " + fire6.height);
		System.out.println("this is fire6 instance:color " + fire6.color);
		System.out.println("this is fire6 instance:material " + fire6.material);
		System.out.println("this is fire6 instance:type " + fire6.type);
		System.out.println("this is fire6 instance:intensity " + fire6.intensity);
		System.out.println("this is fire6 instance:source " + fire6.source);
		System.out.println("this is fire6 instance:spreadRate " + fire6.spreadRate);
		System.out.println("this is fire6 instance:temperature " + fire6.temperature);
		System.out.println("this is fire6 instance:smoke " + fire6.smoke);
		System.out.println("this is fire6 instance:extinguisher " + fire6.extinguisher);
		System.out.println("this is fire6 instance:location " + fire6.location);
		System.out.println("this is fire6 instance:cause " + fire6.cause);
		System.out.println("this is fire6 instance:status " + fire6.status);
	}
}