class ProjectorRunner {
	public static void main(String... values) {
		Projector projector1 = new Projector();
		Projector projector2 = new Projector();
		Projector projector3 = new Projector();
		Projector projector4 = new Projector();
		Projector projector5 = new Projector();
		Projector projector6 = new Projector();
		Projector projector7 = new Projector();
		Projector projector8 = new Projector();
		Projector projector9 = new Projector();
		Projector projector10 = new Projector();

		projector1.brand = "Epson";
		projector1.lumens = 3000;
		projector1.resolution = "1080p";
		projector1.connectivity = "HDMI";
		projector1.throwRatio = 2;
		projector1.displayTechnology = "LCD";
		projector1.aspectRatio = "16:9";
		projector1.contrastRatio = 15000;
		projector1.lampType = "LED";
		projector1.compatibility = "Windows";

		System.out.println("this is projector1 instance:length " + projector1.length);
		System.out.println("this is projector1 instance:width " + projector1.width);
		System.out.println("this is projector1 instance:height " + projector1.height);
		System.out.println("this is projector1 instance:color " + projector1.color);
		System.out.println("this is projector1 instance:material " + projector1.material);
		System.out.println("this is projector1 instance:brand " + projector1.brand);
		System.out.println("this is projector1 instance:lumens " + projector1.lumens);
		System.out.println("this is projector1 instance:resolution " + projector1.resolution);
		System.out.println("this is projector1 instance:connectivity " + projector1.connectivity);
		System.out.println("this is projector1 instance:throwRatio " + projector1.throwRatio);
		System.out.println("this is projector1 instance:displayTechnology " + projector1.displayTechnology);
		System.out.println("this is projector1 instance:aspectRatio " + projector1.aspectRatio);
		System.out.println("this is projector1 instance:contrastRatio " + projector1.contrastRatio);
		System.out.println("this is projector1 instance:lampType " + projector1.lampType);
		System.out.println("this is projector1 instance:compatibility " + projector1.compatibility);

		projector2.brand = "BenQ";
		projector2.lumens = 4000;
		projector2.resolution = "4K";
		projector2.connectivity = "Wireless";
		projector2.throwRatio = 3;
		projector2.displayTechnology = "DLP";
		projector2.aspectRatio = "16:9";
		projector2.contrastRatio = 30000;
		projector2.lampType = "Laser";
		projector2.compatibility = "Mac";

		System.out.println("this is projector2 instance:length " + projector2.length);
		System.out.println("this is projector2 instance:width " + projector2.width);
		System.out.println("this is projector2 instance:height " + projector2.height);
		System.out.println("this is projector2 instance:color " + projector2.color);
		System.out.println("this is projector2 instance:material " + projector2.material);
		System.out.println("this is projector2 instance:brand " + projector2.brand);
		System.out.println("this is projector2 instance:lumens " + projector2.lumens);
		System.out.println("this is projector2 instance:resolution " + projector2.resolution);
		System.out.println("this is projector2 instance:connectivity " + projector2.connectivity);
		System.out.println("this is projector2 instance:throwRatio " + projector2.throwRatio);
		System.out.println("this is projector2 instance:displayTechnology " + projector2.displayTechnology);
		System.out.println("this is projector2 instance:aspectRatio " + projector2.aspectRatio);
		System.out.println("this is projector2 instance:contrastRatio " + projector2.contrastRatio);
		System.out.println("this is projector2 instance:lampType " + projector2.lampType);
		System.out.println("this is projector2 instance:compatibility " + projector2.compatibility);

		projector3.brand = "Sony";
		projector3.lumens = 2000;
		projector3.resolution = "720p";
		projector3.connectivity = "VGA";
		projector3.throwRatio = 1;
		projector3.displayTechnology = "LCOS";
		projector3.aspectRatio = "4:3";
		projector3.contrastRatio = 10000;
		projector3.lampType = "UHP";
		projector3.compatibility = "Linux";

		System.out.println("this is projector3 instance:length " + projector3.length);
		System.out.println("this is projector3 instance:width " + projector3.width);
		System.out.println("this is projector3 instance:height " + projector3.height);
		System.out.println("this is projector3 instance:color " + projector3.color);
		System.out.println("this is projector3 instance:material " + projector3.material);
		System.out.println("this is projector3 instance:brand " + projector3.brand);
		System.out.println("this is projector3 instance:lumens " + projector3.lumens);
		System.out.println("this is projector3 instance:resolution " + projector3.resolution);
		System.out.println("this is projector3 instance:connectivity " + projector3.connectivity);
		System.out.println("this is projector3 instance:throwRatio " + projector3.throwRatio);
		System.out.println("this is projector3 instance:displayTechnology " + projector3.displayTechnology);
		System.out.println("this is projector3 instance:aspectRatio " + projector3.aspectRatio);
		System.out.println("this is projector3 instance:contrastRatio " + projector3.contrastRatio);
		System.out.println("this is projector3 instance:lampType " + projector3.lampType);
		System.out.println("this is projector3 instance:compatibility " + projector3.compatibility);

		projector4.brand = "Optoma";
		projector4.lumens = 5000;
		projector4.resolution = "1080p";
		projector4.connectivity = "HDMI";
		projector4.throwRatio = 2;
		projector4.displayTechnology = "DLP";
		projector4.aspectRatio = "16:9";
		projector4.contrastRatio = 25000;
		projector4.lampType = "LED";
		projector4.compatibility = "Windows";

		System.out.println("this is projector4 instance:length " + projector4.length);
		System.out.println("this is projector4 instance:width " + projector4.width);
		System.out.println("this is projector4 instance:height " + projector4.height);
		System.out.println("this is projector4 instance:color " + projector4.color);
		System.out.println("this is projector4 instance:material " + projector4.material);
		System.out.println("this is projector4 instance:brand " + projector4.brand);
		System.out.println("this is projector4 instance:lumens " + projector4.lumens);
		System.out.println("this is projector4 instance:resolution " + projector4.resolution);
		System.out.println("this is projector4 instance:connectivity " + projector4.connectivity);
		System.out.println("this is projector4 instance:throwRatio " + projector4.throwRatio);
		System.out.println("this is projector4 instance:displayTechnology " + projector4.displayTechnology);
		System.out.println("this is projector4 instance:aspectRatio " + projector4.aspectRatio);
		System.out.println("this is projector4 instance:contrastRatio " + projector4.contrastRatio);
		System.out.println("this is projector4 instance:lampType " + projector4.lampType);
		System.out.println("this is projector4 instance:compatibility " + projector4.compatibility);

		projector5.brand = "ViewSonic";
		projector5.lumens = 3500;
		projector5.resolution = "4K";
		projector5.connectivity = "Bluetooth";
		projector5.throwRatio = 2;
		projector5.displayTechnology = "LCD";
		projector5.aspectRatio = "16:10";
		projector5.contrastRatio = 20000;
		projector5.lampType = "Laser";
		projector5.compatibility = "Windows";

		System.out.println("this is projector5 instance:length " + projector5.length);
		System.out.println("this is projector5 instance:width " + projector5.width);
		System.out.println("this is projector5 instance:height " + projector5.height);
		System.out.println("this is projector5 instance:color " + projector5.color);
		System.out.println("this is projector5 instance:material " + projector5.material);
		System.out.println("this is projector5 instance:brand " + projector5.brand);
		System.out.println("this is projector5 instance:lumens " + projector5.lumens);
		System.out.println("this is projector5 instance:resolution " + projector5.resolution);
		System.out.println("this is projector5 instance:connectivity " + projector5.connectivity);
		System.out.println("this is projector5 instance:throwRatio " + projector5.throwRatio);
		System.out.println("this is projector5 instance:displayTechnology " + projector5.displayTechnology);
		System.out.println("this is projector5 instance:aspectRatio " + projector5.aspectRatio);
		System.out.println("this is projector5 instance:contrastRatio " + projector5.contrastRatio);
		System.out.println("this is projector5 instance:lampType " + projector5.lampType);
		System.out.println("this is projector5 instance:compatibility " + projector5.compatibility);

		projector6.brand = "Panasonic";
		projector6.lumens = 6000;
		projector6.resolution = "1080p";
		projector6.connectivity = "HDMI";
		projector6.throwRatio = 3;
		projector6.displayTechnology = "LCD";
		projector6.aspectRatio = "16:9";
		projector6.contrastRatio = 18000;
		projector6.lampType = "UHP";
		projector6.compatibility = "Mac";

		System.out.println("this is projector6 instance:length " + projector6.length);
		System.out.println("this is projector6 instance:width " + projector6.width);
		System.out.println("this is projector6 instance:height " + projector6.height);
		System.out.println("this is projector6 instance:color " + projector6.color);
		System.out.println("this is projector6 instance:material " + projector6.material);
		System.out.println("this is projector6 instance:brand " + projector6.brand);
		System.out.println("this is projector6 instance:lumens " + projector6.lumens);
		System.out.println("this is projector6 instance:resolution " + projector6.resolution);
		System.out.println("this is projector6 instance:connectivity " + projector6.connectivity);
		System.out.println("this is projector6 instance:throwRatio " + projector6.throwRatio);
		System.out.println("this is projector6 instance:displayTechnology " + projector6.displayTechnology);
		System.out.println("this is projector6 instance:aspectRatio " + projector6.aspectRatio);
		System.out.println("this is projector6 instance:contrastRatio " + projector6.contrastRatio);
		System.out.println("this is projector6 instance:lampType " + projector6.lampType);
		System.out.println("this is projector6 instance:compatibility " + projector6.compatibility);

		projector7.brand = "Acer";
		projector7.lumens = 2500;
		projector7.resolution = "720p";
		projector7.connectivity = "VGA";
		projector7.throwRatio = 1;
		projector7.displayTechnology = "DLP";
		projector7.aspectRatio = "4:3";
		projector7.contrastRatio = 12000;
		projector7.lampType = "LED";
		projector7.compatibility = "Windows";

		System.out.println("this is projector7 instance:length " + projector7.length);
		System.out.println("this is projector7 instance:width " + projector7.width);
		System.out.println("this is projector7 instance:height " + projector7.height);
		System.out.println("this is projector7 instance:color " + projector7.color);
		System.out.println("this is projector7 instance:material " + projector7.material);
		System.out.println("this is projector7 instance:brand " + projector7.brand);
		System.out.println("this is projector7 instance:lumens " + projector7.lumens);
		System.out.println("this is projector7 instance:resolution " + projector7.resolution);
		System.out.println("this is projector7 instance:connectivity " + projector7.connectivity);
		System.out.println("this is projector7 instance:throwRatio " + projector7.throwRatio);
		System.out.println("this is projector7 instance:displayTechnology " + projector7.displayTechnology);
		System.out.println("this is projector7 instance:aspectRatio " + projector7.aspectRatio);
		System.out.println("this is projector7 instance:contrastRatio " + projector7.contrastRatio);
		System.out.println("this is projector7 instance:lampType " + projector7.lampType);
		System.out.println("this is projector7 instance:compatibility " + projector7.compatibility);

		projector8.brand = "LG";
		projector8.lumens = 1500;
		projector8.resolution = "4K";
		projector8.connectivity = "Wireless";
		projector8.throwRatio = 1;
		projector8.displayTechnology = "LCOS";
		projector8.aspectRatio = "16:9";
		projector8.contrastRatio = 50000;
		projector8.lampType = "Laser";
		projector8.compatibility = "Linux";

		System.out.println("this is projector8 instance:length " + projector8.length);
		System.out.println("this is projector8 instance:width " + projector8.width);
		System.out.println("this is projector8 instance:height " + projector8.height);
		System.out.println("this is projector8 instance:color " + projector8.color);
		System.out.println("this is projector8 instance:material " + projector8.material);
		System.out.println("this is projector8 instance:brand " + projector8.brand);
		System.out.println("this is projector8 instance:lumens " + projector8.lumens);
		System.out.println("this is projector8 instance:resolution " + projector8.resolution);
		System.out.println("this is projector8 instance:connectivity " + projector8.connectivity);
		System.out.println("this is projector8 instance:throwRatio " + projector8.throwRatio);
		System.out.println("this is projector8 instance:displayTechnology " + projector8.displayTechnology);
		System.out.println("this is projector8 instance:aspectRatio " + projector8.aspectRatio);
		System.out.println("this is projector8 instance:contrastRatio " + projector8.contrastRatio);
		System.out.println("this is projector8 instance:lampType " + projector8.lampType);
		System.out.println("this is projector8 instance:compatibility " + projector8.compatibility);

		projector9.brand = "Samsung";
		projector9.lumens = 2200;
		projector9.resolution = "1080p";
		projector9.connectivity = "Bluetooth";
		projector9.throwRatio = 2;
		projector9.displayTechnology = "DLP";
		projector9.aspectRatio = "16:9";
		projector9.contrastRatio = 22000;
		projector9.lampType = "LED";
		projector9.compatibility = "Windows";

		System.out.println("this is projector9 instance:length " + projector9.length);
		System.out.println("this is projector9 instance:width " + projector9.width);
		System.out.println("this is projector9 instance:height " + projector9.height);
		System.out.println("this is projector9 instance:color " + projector9.color);
		System.out.println("this is projector9 instance:material " + projector9.material);
		System.out.println("this is projector9 instance:brand " + projector9.brand);
		System.out.println("this is projector9 instance:lumens " + projector9.lumens);
		System.out.println("this is projector9 instance:resolution " + projector9.resolution);
		System.out.println("this is projector9 instance:connectivity " + projector9.connectivity);
		System.out.println("this is projector9 instance:throwRatio " + projector9.throwRatio);
		System.out.println("this is projector9 instance:displayTechnology " + projector9.displayTechnology);
		System.out.println("this is projector9 instance:aspectRatio " + projector9.aspectRatio);
		System.out.println("this is projector9 instance:contrastRatio " + projector9.contrastRatio);
		System.out.println("this is projector9 instance:lampType " + projector9.lampType);
		System.out.println("this is projector9 instance:compatibility " + projector9.compatibility);

		projector10.brand = "Hitachi";
		projector10.lumens = 4500;
		projector10.resolution = "4K";
		projector10.connectivity = "HDMI";
		projector10.throwRatio = 3;
		projector10.displayTechnology = "LCD";
		projector10.aspectRatio = "16:9";
		projector10.contrastRatio = 35000;
		projector10.lampType = "UHP";
		projector10.compatibility = "Mac";

		System.out.println("this is projector10 instance:length " + projector10.length);
		System.out.println("this is projector10 instance:width " + projector10.width);
		System.out.println("this is projector10 instance:height " + projector10.height);
		System.out.println("this is projector10 instance:color " + projector10.color);
		System.out.println("this is projector10 instance:material " + projector10.material);
		System.out.println("this is projector10 instance:brand " + projector10.brand);
		System.out.println("this is projector10 instance:lumens " + projector10.lumens);
		System.out.println("this is projector10 instance:resolution " + projector10.resolution);
		System.out.println("this is projector10 instance:connectivity " + projector10.connectivity);
		System.out.println("this is projector10 instance:throwRatio " + projector10.throwRatio);
		System.out.println("this is projector10 instance:displayTechnology " + projector10.displayTechnology);
		System.out.println("this is projector10 instance:aspectRatio " + projector10.aspectRatio);
		System.out.println("this is projector10 instance:contrastRatio " + projector10.contrastRatio);
		System.out.println("this is projector10 instance:lampType " + projector10.lampType);
		System.out.println("this is projector10 instance:compatibility " + projector10.compatibility);

		projector6 = projector7;
		System.out.println("this is projector6 instance:length " + projector6.length);
		System.out.println("this is projector6 instance:width " + projector6.width);
		System.out.println("this is projector6 instance:height " + projector6.height);
		System.out.println("this is projector6 instance:color " + projector6.color);
		System.out.println("this is projector6 instance:material " + projector6.material);
		System.out.println("this is projector6 instance:brand " + projector6.brand);
		System.out.println("this is projector6 instance:lumens " + projector6.lumens);
		System.out.println("this is projector6 instance:resolution " + projector6.resolution);
		System.out.println("this is projector6 instance:connectivity " + projector6.connectivity);
		System.out.println("this is projector6 instance:throwRatio " + projector6.throwRatio);
		System.out.println("this is projector6 instance:displayTechnology " + projector6.displayTechnology);
		System.out.println("this is projector6 instance:aspectRatio " + projector6.aspectRatio);
		System.out.println("this is projector6 instance:contrastRatio " + projector6.contrastRatio);
		System.out.println("this is projector6 instance:lampType " + projector6.lampType);
		System.out.println("this is projector6 instance:compatibility " + projector6.compatibility);
	}
}