class XboxRunner {
	public static void main(String... values) {
		Xbox xbox1 = new Xbox();
		Xbox xbox2 = new Xbox();
		Xbox xbox3 = new Xbox();
		Xbox xbox4 = new Xbox();
		Xbox xbox5 = new Xbox();
		Xbox xbox6 = new Xbox();
		Xbox xbox7 = new Xbox();
		Xbox xbox8 = new Xbox();
		Xbox xbox9 = new Xbox();
		Xbox xbox10 = new Xbox();

		xbox1.brand = "Microsoft";
		xbox1.model = "SeriesX";
		xbox1.storageGB = 1000;
		xbox1.resolution = "4K";
		xbox1.connectivity = "WiFi";
		xbox1.ramGB = 16;
		xbox1.processor = "ZenPlus";
		xbox1.gpu = "RDNA2";
		xbox1.discDrive = "UHDBluRay";
		xbox1.generation = "9th";

		System.out.println("this is xbox1 instance:length " + xbox1.length);
		System.out.println("this is xbox1 instance:width " + xbox1.width);
		System.out.println("this is xbox1 instance:height " + xbox1.height);
		System.out.println("this is xbox1 instance:color " + xbox1.color);
		System.out.println("this is xbox1 instance:material " + xbox1.material);
		System.out.println("this is xbox1 instance:brand " + xbox1.brand);
		System.out.println("this is xbox1 instance:model " + xbox1.model);
		System.out.println("this is xbox1 instance:storageGB " + xbox1.storageGB);
		System.out.println("this is xbox1 instance:resolution " + xbox1.resolution);
		System.out.println("this is xbox1 instance:connectivity " + xbox1.connectivity);
		System.out.println("this is xbox1 instance:ramGB " + xbox1.ramGB);
		System.out.println("this is xbox1 instance:processor " + xbox1.processor);
		System.out.println("this is xbox1 instance:gpu " + xbox1.gpu);
		System.out.println("this is xbox1 instance:discDrive " + xbox1.discDrive);
		System.out.println("this is xbox1 instance:generation " + xbox1.generation);

		xbox2.brand = "Microsoft";
		xbox2.model = "SeriesS";
		xbox2.storageGB = 512;
		xbox2.resolution = "1440p";
		xbox2.connectivity = "WiFi";
		xbox2.ramGB = 10;
		xbox2.processor = "ZenPlus";
		xbox2.gpu = "RDNA2";
		xbox2.discDrive = "DiscLess";
		xbox2.generation = "9th";

		System.out.println("this is xbox2 instance:length " + xbox2.length);
		System.out.println("this is xbox2 instance:width " + xbox2.width);
		System.out.println("this is xbox2 instance:height " + xbox2.height);
		System.out.println("this is xbox2 instance:color " + xbox2.color);
		System.out.println("this is xbox2 instance:material " + xbox2.material);
		System.out.println("this is xbox2 instance:brand " + xbox2.brand);
		System.out.println("this is xbox2 instance:model " + xbox2.model);
		System.out.println("this is xbox2 instance:storageGB " + xbox2.storageGB);
		System.out.println("this is xbox2 instance:resolution " + xbox2.resolution);
		System.out.println("this is xbox2 instance:connectivity " + xbox2.connectivity);
		System.out.println("this is xbox2 instance:ramGB " + xbox2.ramGB);
		System.out.println("this is xbox2 instance:processor " + xbox2.processor);
		System.out.println("this is xbox2 instance:gpu " + xbox2.gpu);
		System.out.println("this is xbox2 instance:discDrive " + xbox2.discDrive);
		System.out.println("this is xbox2 instance:generation " + xbox2.generation);

		xbox3.brand = "Microsoft";
		xbox3.model = "OneX";
		xbox3.storageGB = 1000;
		xbox3.resolution = "4K";
		xbox3.connectivity = "WiFi";
		xbox3.ramGB = 12;
		xbox3.processor = "Jaguar";
		xbox3.gpu = "GCN";
		xbox3.discDrive = "BluRay";
		xbox3.generation = "8th";

		System.out.println("this is xbox3 instance:length " + xbox3.length);
		System.out.println("this is xbox3 instance:width " + xbox3.width);
		System.out.println("this is xbox3 instance:height " + xbox3.height);
		System.out.println("this is xbox3 instance:color " + xbox3.color);
		System.out.println("this is xbox3 instance:material " + xbox3.material);
		System.out.println("this is xbox3 instance:brand " + xbox3.brand);
		System.out.println("this is xbox3 instance:model " + xbox3.model);
		System.out.println("this is xbox3 instance:storageGB " + xbox3.storageGB);
		System.out.println("this is xbox3 instance:resolution " + xbox3.resolution);
		System.out.println("this is xbox3 instance:connectivity " + xbox3.connectivity);
		System.out.println("this is xbox3 instance:ramGB " + xbox3.ramGB);
		System.out.println("this is xbox3 instance:processor " + xbox3.processor);
		System.out.println("this is xbox3 instance:gpu " + xbox3.gpu);
		System.out.println("this is xbox3 instance:discDrive " + xbox3.discDrive);
		System.out.println("this is xbox3 instance:generation " + xbox3.generation);

		xbox4.brand = "Microsoft";
		xbox4.model = "OneS";
		xbox4.storageGB = 500;
		xbox4.resolution = "1080p";
		xbox4.connectivity = "WiFi";
		xbox4.ramGB = 8;
		xbox4.processor = "Jaguar";
		xbox4.gpu = "GCN";
		xbox4.discDrive = "BluRay";
		xbox4.generation = "8th";

		System.out.println("this is xbox4 instance:length " + xbox4.length);
		System.out.println("this is xbox4 instance:width " + xbox4.width);
		System.out.println("this is xbox4 instance:height " + xbox4.height);
		System.out.println("this is xbox4 instance:color " + xbox4.color);
		System.out.println("this is xbox4 instance:material " + xbox4.material);
		System.out.println("this is xbox4 instance:brand " + xbox4.brand);
		System.out.println("this is xbox4 instance:model " + xbox4.model);
		System.out.println("this is xbox4 instance:storageGB " + xbox4.storageGB);
		System.out.println("this is xbox4 instance:resolution " + xbox4.resolution);
		System.out.println("this is xbox4 instance:connectivity " + xbox4.connectivity);
		System.out.println("this is xbox4 instance:ramGB " + xbox4.ramGB);
		System.out.println("this is xbox4 instance:processor " + xbox4.processor);
		System.out.println("this is xbox4 instance:gpu " + xbox4.gpu);
		System.out.println("this is xbox4 instance:discDrive " + xbox4.discDrive);
		System.out.println("this is xbox4 instance:generation " + xbox4.generation);

		xbox5.brand = "Microsoft";
		xbox5.model = "360";
		xbox5.storageGB = 250;
		xbox5.resolution = "1080p";
		xbox5.connectivity = "Ethernet";
		xbox5.ramGB = 1;
		xbox5.processor = "Xenon";
		xbox5.gpu = "Xenos";
		xbox5.discDrive = "DVD";
		xbox5.generation = "7th";

		System.out.println("this is xbox5 instance:length " + xbox5.length);
		System.out.println("this is xbox5 instance:width " + xbox5.width);
		System.out.println("this is xbox5 instance:height " + xbox5.height);
		System.out.println("this is xbox5 instance:color " + xbox5.color);
		System.out.println("this is xbox5 instance:material " + xbox5.material);
		System.out.println("this is xbox5 instance:brand " + xbox5.brand);
		System.out.println("this is xbox5 instance:model " + xbox5.model);
		System.out.println("this is xbox5 instance:storageGB " + xbox5.storageGB);
		System.out.println("this is xbox5 instance:resolution " + xbox5.resolution);
		System.out.println("this is xbox5 instance:connectivity " + xbox5.connectivity);
		System.out.println("this is xbox5 instance:ramGB " + xbox5.ramGB);
		System.out.println("this is xbox5 instance:processor " + xbox5.processor);
		System.out.println("this is xbox5 instance:gpu " + xbox5.gpu);
		System.out.println("this is xbox5 instance:discDrive " + xbox5.discDrive);
		System.out.println("this is xbox5 instance:generation " + xbox5.generation);

		xbox6.brand = "Microsoft";
		xbox6.model = "Original";
		xbox6.storageGB = 8;
		xbox6.resolution = "480p";
		xbox6.connectivity = "Ethernet";
		xbox6.ramGB = 1;
		xbox6.processor = "Pentium3";
		xbox6.gpu = "NV2A";
		xbox6.discDrive = "DVD";
		xbox6.generation = "6th";

		System.out.println("this is xbox6 instance:length " + xbox6.length);
		System.out.println("this is xbox6 instance:width " + xbox6.width);
		System.out.println("this is xbox6 instance:height " + xbox6.height);
		System.out.println("this is xbox6 instance:color " + xbox6.color);
		System.out.println("this is xbox6 instance:material " + xbox6.material);
		System.out.println("this is xbox6 instance:brand " + xbox6.brand);
		System.out.println("this is xbox6 instance:model " + xbox6.model);
		System.out.println("this is xbox6 instance:storageGB " + xbox6.storageGB);
		System.out.println("this is xbox6 instance:resolution " + xbox6.resolution);
		System.out.println("this is xbox6 instance:connectivity " + xbox6.connectivity);
		System.out.println("this is xbox6 instance:ramGB " + xbox6.ramGB);
		System.out.println("this is xbox6 instance:processor " + xbox6.processor);
		System.out.println("this is xbox6 instance:gpu " + xbox6.gpu);
		System.out.println("this is xbox6 instance:discDrive " + xbox6.discDrive);
		System.out.println("this is xbox6 instance:generation " + xbox6.generation);

		xbox7.brand = "Microsoft";
		xbox7.model = "SeriesXSpecialEdition";
		xbox7.storageGB = 2000;
		xbox7.resolution = "8K";
		xbox7.connectivity = "WiFi6";
		xbox7.ramGB = 16;
		xbox7.processor = "ZenPlus";
		xbox7.gpu = "RDNA2";
		xbox7.discDrive = "UHDBluRay";
		xbox7.generation = "9th";

		System.out.println("this is xbox7 instance:length " + xbox7.length);
		System.out.println("this is xbox7 instance:width " + xbox7.width);
		System.out.println("this is xbox7 instance:height " + xbox7.height);
		System.out.println("this is xbox7 instance:color " + xbox7.color);
		System.out.println("this is xbox7 instance:material " + xbox7.material);
		System.out.println("this is xbox7 instance:brand " + xbox7.brand);
		System.out.println("this is xbox7 instance:model " + xbox7.model);
		System.out.println("this is xbox7 instance:storageGB " + xbox7.storageGB);
		System.out.println("this is xbox7 instance:resolution " + xbox7.resolution);
		System.out.println("this is xbox7 instance:connectivity " + xbox7.connectivity);
		System.out.println("this is xbox7 instance:ramGB " + xbox7.ramGB);
		System.out.println("this is xbox7 instance:processor " + xbox7.processor);
		System.out.println("this is xbox7 instance:gpu " + xbox7.gpu);
		System.out.println("this is xbox7 instance:discDrive " + xbox7.discDrive);
		System.out.println("this is xbox7 instance:generation " + xbox7.generation);

		xbox8.brand = "Microsoft";
		xbox8.model = "OneAllDigital";
		xbox8.storageGB = 1000;
		xbox8.resolution = "4K";
		xbox8.connectivity = "WiFi";
		xbox8.ramGB = 8;
		xbox8.processor = "Jaguar";
		xbox8.gpu = "GCN";
		xbox8.discDrive = "DiscLess";
		xbox8.generation = "8th";

		System.out.println("this is xbox8 instance:length " + xbox8.length);
		System.out.println("this is xbox8 instance:width " + xbox8.width);
		System.out.println("this is xbox8 instance:height " + xbox8.height);
		System.out.println("this is xbox8 instance:color " + xbox8.color);
		System.out.println("this is xbox8 instance:material " + xbox8.material);
		System.out.println("this is xbox8 instance:brand " + xbox8.brand);
		System.out.println("this is xbox8 instance:model " + xbox8.model);
		System.out.println("this is xbox8 instance:storageGB " + xbox8.storageGB);
		System.out.println("this is xbox8 instance:resolution " + xbox8.resolution);
		System.out.println("this is xbox8 instance:connectivity " + xbox8.connectivity);
		System.out.println("this is xbox8 instance:ramGB " + xbox8.ramGB);
		System.out.println("this is xbox8 instance:processor " + xbox8.processor);
		System.out.println("this is xbox8 instance:gpu " + xbox8.gpu);
		System.out.println("this is xbox8 instance:discDrive " + xbox8.discDrive);
		System.out.println("this is xbox8 instance:generation " + xbox8.generation);

		xbox9.brand = "Microsoft";
		xbox9.model = "360Elite";
		xbox9.storageGB = 120;
		xbox9.resolution = "1080p";
		xbox9.connectivity = "WiFi";
		xbox9.ramGB = 1;
		xbox9.processor = "Xenon";
		xbox9.gpu = "Xenos";
		xbox9.discDrive = "DVD";
		xbox9.generation = "7th";

		System.out.println("this is xbox9 instance:length " + xbox9.length);
		System.out.println("this is xbox9 instance:width " + xbox9.width);
		System.out.println("this is xbox9 instance:height " + xbox9.height);
		System.out.println("this is xbox9 instance:color " + xbox9.color);
		System.out.println("this is xbox9 instance:material " + xbox9.material);
		System.out.println("this is xbox9 instance:brand " + xbox9.brand);
		System.out.println("this is xbox9 instance:model " + xbox9.model);
		System.out.println("this is xbox9 instance:storageGB " + xbox9.storageGB);
		System.out.println("this is xbox9 instance:resolution " + xbox9.resolution);
		System.out.println("this is xbox9 instance:connectivity " + xbox9.connectivity);
		System.out.println("this is xbox9 instance:ramGB " + xbox9.ramGB);
		System.out.println("this is xbox9 instance:processor " + xbox9.processor);
		System.out.println("this is xbox9 instance:gpu " + xbox9.gpu);
		System.out.println("this is xbox9 instance:discDrive " + xbox9.discDrive);
		System.out.println("this is xbox9 instance:generation " + xbox9.generation);

		xbox10.brand = "Microsoft";
		xbox10.model = "SeriesSCarbon";
		xbox10.storageGB = 512;
		xbox10.resolution = "1440p";
		xbox10.connectivity = "WiFi6";
		xbox10.ramGB = 10;
		xbox10.processor = "ZenPlus";
		xbox10.gpu = "RDNA2";
		xbox10.discDrive = "DiscLess";
		xbox10.generation = "9th";

		System.out.println("this is xbox10 instance:length " + xbox10.length);
		System.out.println("this is xbox10 instance:width " + xbox10.width);
		System.out.println("this is xbox10 instance:height " + xbox10.height);
		System.out.println("this is xbox10 instance:color " + xbox10.color);
		System.out.println("this is xbox10 instance:material " + xbox10.material);
		System.out.println("this is xbox10 instance:brand " + xbox10.brand);
		System.out.println("this is xbox10 instance:model " + xbox10.model);
		System.out.println("this is xbox10 instance:storageGB " + xbox10.storageGB);
		System.out.println("this is xbox10 instance:resolution " + xbox10.resolution);
		System.out.println("this is xbox10 instance:connectivity " + xbox10.connectivity);
		System.out.println("this is xbox10 instance:ramGB " + xbox10.ramGB);
		System.out.println("this is xbox10 instance:processor " + xbox10.processor);
		System.out.println("this is xbox10 instance:gpu " + xbox10.gpu);
		System.out.println("this is xbox10 instance:discDrive " + xbox10.discDrive);
		System.out.println("this is xbox10 instance:generation " + xbox10.generation);

		xbox6 = xbox7;
		System.out.println("this is xbox6 instance:length " + xbox6.length);
		System.out.println("this is xbox6 instance:width " + xbox6.width);
		System.out.println("this is xbox6 instance:height " + xbox6.height);
		System.out.println("this is xbox6 instance:color " + xbox6.color);
		System.out.println("this is xbox6 instance:material " + xbox6.material);
		System.out.println("this is xbox6 instance:brand " + xbox6.brand);
		System.out.println("this is xbox6 instance:model " + xbox6.model);
		System.out.println("this is xbox6 instance:storageGB " + xbox6.storageGB);
		System.out.println("this is xbox6 instance:resolution " + xbox6.resolution);
		System.out.println("this is xbox6 instance:connectivity " + xbox6.connectivity);
		System.out.println("this is xbox6 instance:ramGB " + xbox6.ramGB);
		System.out.println("this is xbox6 instance:processor " + xbox6.processor);
		System.out.println("this is xbox6 instance:gpu " + xbox6.gpu);
		System.out.println("this is xbox6 instance:discDrive " + xbox6.discDrive);
		System.out.println("this is xbox6 instance:generation " + xbox6.generation);
	}
}