class CabinetRunner{
	public static void main(String... values){
		Cabinet cabinet1 = new Cabinet();
		Cabinet cabinet2 = new Cabinet();
		Cabinet cabinet3 = new Cabinet();
		Cabinet cabinet4 = new Cabinet();
		Cabinet cabinet5 = new Cabinet();
		Cabinet cabinet6 = new Cabinet();
		Cabinet cabinet7 = new Cabinet();
		Cabinet cabinet8 = new Cabinet();
		Cabinet cabinet9 = new Cabinet();
		Cabinet cabinet10 = new Cabinet();
		cabinet1.shelves= 12;
		cabinet1.thickness = 23.9;
		cabinet1.doorHeight= 34.5;
		cabinet1.doorWidth = 36.0;
		cabinet1.drawers = 36;
		cabinet1.shelfHeight= 67;
		cabinet1.shelfWidth= 45;
		cabinet1.shelfDepth= 56;
		cabinet1.weight = 49.6;
		cabinet1.lockBrand= "Sindhu";
		System.out.println("this is cabinet1 instance:height " +cabinet1.height);
		System.out.println("this is cabinet1 instance:width " +cabinet1.width);
		System.out.println("this is cabinet1 instance:depth " +cabinet1.depth);
		System.out.println("this is cabinet1 instance:shelves " +cabinet1.shelves);
		System.out.println("this is cabinet1 instance:thickness " +cabinet1.thickness);
		System.out.println("this is cabinet1 instance:doorHeight " +cabinet1.doorHeight);
		System.out.println("this is cabinet1 instance:doorWidth " +cabinet1.doorWidth);
		System.out.println("this is cabinet1 instance:drawers " +cabinet1.drawers);
		System.out.println("this is cabinet1 instance:ShelfHeight " +cabinet1.shelfHeight);
		System.out.println("this is cabinet1 instance:shelfwidth " +cabinet1.shelfWidth);
		System.out.println("this is cabinet1 instance:ShelfDepth " +cabinet1.shelfDepth);
		System.out.println("this is cabinet1 instance:weight " +cabinet1.weight);
		System.out.println("this is cabinet1 instance:material " +cabinet1.material);
		System.out.println("this is cabinet1 instance:color " +cabinet1.color);
		System.out.println("this is cabinet1 instance:lockBrand " +cabinet1.lockBrand);
		
		cabinet2.shelves= 24;
		cabinet2.thickness = 34.2;
		cabinet2.doorHeight= 12.9;
		cabinet2.doorWidth = 57.9;
		cabinet2.drawers = 63;
		cabinet2.shelfHeight= 76;
		cabinet2.shelfWidth= 54;
		cabinet2.shelfDepth= 65;
		cabinet2.weight = 89.45;
		cabinet2.lockBrand= "Puneeth";
		System.out.println("this is cabinet2 instance:height " +cabinet2.height);
		System.out.println("this is cabinet2 instance:width " +cabinet2.width);
		System.out.println("this is cabinet2 instance:depth " +cabinet2.depth);
		System.out.println("this is cabinet2 instance:shelves " +cabinet2.shelves);
		System.out.println("this is cabinet2 instance:thickness " +cabinet2.thickness);
		System.out.println("this is cabinet2 instance:doorHeight " +cabinet2.doorHeight);
		System.out.println("this is cabinet2 instance:doorWidth " +cabinet2.doorWidth);
		System.out.println("this is cabinet2 instance:drawers " +cabinet2.drawers);
		System.out.println("this is cabinet2 instance:ShelfHeight " +cabinet2.shelfHeight);
		System.out.println("this is cabinet2 instance:shelfwidth " +cabinet2.shelfWidth);
		System.out.println("this is cabinet2 instance:ShelfDepth " +cabinet2.shelfDepth);
		System.out.println("this is cabinet2 instance:weight " +cabinet2.weight);
		System.out.println("this is cabinet2 instance:material " +cabinet2.material);
		System.out.println("this is cabinet2 instance:color " +cabinet2.color);
		System.out.println("this is cabinet2 instance:lockBrand " +cabinet2.lockBrand);
		
		cabinet3.shelves= 3;
		cabinet3.thickness = 96.3;
		cabinet3.doorHeight= 3456.0;
		cabinet3.doorWidth = 789.0;
		cabinet3.drawers = 234;
		cabinet3.shelfHeight= 89;
		cabinet3.shelfWidth= 785;
		cabinet3.shelfDepth= 23;
		cabinet3.weight = 7834;
		cabinet3.lockBrand= "Sannamma";
		System.out.println("this is cabinet3 instance:height " +cabinet3.height);
		System.out.println("this is cabinet3 instance:width " +cabinet3.width);
		System.out.println("this is cabinet3 instance:depth " +cabinet3.depth);
		System.out.println("this is cabinet3 instance:shelves " +cabinet3.shelves);
		System.out.println("this is cabinet3 instance:thickness " +cabinet3.thickness);
		System.out.println("this is cabinet3 instance:doorHeight " +cabinet3.doorHeight);
		System.out.println("this is cabinet3 instance:doorWidth " +cabinet3.doorWidth);
		System.out.println("this is cabinet3 instance:drawers " +cabinet3.drawers);
		System.out.println("this is cabinet3 instance:ShelfHeight " +cabinet3.shelfHeight);
		System.out.println("this is cabinet3 instance:shelfwidth " +cabinet3.shelfWidth);
		System.out.println("this is cabinet3 instance:ShelfDepth " +cabinet3.shelfDepth);
		System.out.println("this is cabinet3 instance:weight " +cabinet3.weight);
		System.out.println("this is cabinet3 instance:material " +cabinet3.material);
		System.out.println("this is cabinet3 instance:color " +cabinet3.color);
		System.out.println("this is cabinet3 instance:lockBrand " +cabinet3.lockBrand);
		
		cabinet4.shelves= 87;
		cabinet4.thickness = 34.9;
		cabinet4.doorHeight= 34.7;
		cabinet4.doorWidth = 36.5;
		cabinet4.drawers = 123;
		cabinet4.shelfHeight= 356;
		cabinet4.shelfWidth= 674;
		cabinet4.shelfDepth= 11;
		cabinet4.weight = 12.9;
		cabinet4.lockBrand= "Venk";
		System.out.println("this is cabinet4 instance:height " +cabinet4.height);
		System.out.println("this is cabinet4 instance:width " +cabinet4.width);
		System.out.println("this is cabinet4 instance:depth " +cabinet4.depth);
		System.out.println("this is cabinet4 instance:shelves " +cabinet4.shelves);
		System.out.println("this is cabinet4 instance:thickness " +cabinet4.thickness);
		System.out.println("this is cabinet4 instance:doorHeight " +cabinet4.doorHeight);
		System.out.println("this is cabinet4 instance:doorWidth " +cabinet4.doorWidth);
		System.out.println("this is cabinet4 instance:drawers " +cabinet4.drawers);
		System.out.println("this is cabinet4 instance:ShelfHeight " +cabinet4.shelfHeight);
		System.out.println("this is cabinet4 instance:shelfwidth " +cabinet4.shelfWidth);
		System.out.println("this is cabinet4 instance:ShelfDepth " +cabinet4.shelfDepth);
		System.out.println("this is cabinet4 instance:weight " +cabinet4.weight);
		System.out.println("this is cabinet4 instance:material " +cabinet4.material);
		System.out.println("this is cabinet4 instance:color " +cabinet4.color);
		System.out.println("this is cabinet4 instance:lockBrand " +cabinet4.lockBrand);

		cabinet5.shelves= 25;
		cabinet5.thickness = 23.09;
		cabinet5.doorHeight= 34.09;
		cabinet5.doorWidth = 23.90;
		cabinet5.drawers = 89;
		cabinet5.shelfHeight= 1234;
		cabinet5.shelfWidth= 28;
		cabinet5.shelfDepth= 12;
		cabinet5.weight = 23.89;
		cabinet5.lockBrand= "Thirum";
		System.out.println("this is cabinet5 instance:height " +cabinet5.height);
		System.out.println("this is cabinet5 instance:width " +cabinet5.width);
		System.out.println("this is cabinet5 instance:depth " +cabinet5.depth);
		System.out.println("this is cabinet5 instance:shelves " +cabinet5.shelves);
		System.out.println("this is cabinet5 instance:thickness " +cabinet5.thickness);
		System.out.println("this is cabinet5 instance:doorHeight " +cabinet5.doorHeight);
		System.out.println("this is cabinet5 instance:doorWidth " +cabinet5.doorWidth);
		System.out.println("this is cabinet5 instance:drawers " +cabinet5.drawers);
		System.out.println("this is cabinet5 instance:ShelfHeight " +cabinet5.shelfHeight);
		System.out.println("this is cabinet5 instance:shelfwidth " +cabinet5.shelfWidth);
		System.out.println("this is cabinet5 instance:ShelfDepth " +cabinet5.shelfDepth);
		System.out.println("this is cabinet5 instance:weight " +cabinet5.weight);
		System.out.println("this is cabinet5 instance:material " +cabinet5.material);
		System.out.println("this is cabinet5 instance:color " +cabinet5.color);
		System.out.println("this is cabinet5 instance:lockBrand " +cabinet5.lockBrand);
		
		cabinet6.shelves= 40;
		cabinet6.thickness = 21.5;
		cabinet6.doorHeight= 55.0;
		cabinet6.doorWidth = 32.2;
		cabinet6.drawers = 20;
		cabinet6.shelfHeight= 60;
		cabinet6.shelfWidth= 48;
		cabinet6.shelfDepth= 30;
		cabinet6.weight = 35.5;
		cabinet6.lockBrand= "Rav";

		System.out.println("this is cabinet6 instance:height " +cabinet6.height);
		System.out.println("this is cabinet6 instance:width " +cabinet6.width);
		System.out.println("this is cabinet6 instance:depth " +cabinet6.depth);
		System.out.println("this is cabinet6 instance:shelves " +cabinet6.shelves);
		System.out.println("this is cabinet6 instance:thickness " +cabinet6.thickness);
		System.out.println("this is cabinet6 instance:doorHeight " +cabinet6.doorHeight);
		System.out.println("this is cabinet6 instance:doorWidth " +cabinet6.doorWidth);
		System.out.println("this is cabinet6 instance:drawers " +cabinet6.drawers);
		System.out.println("this is cabinet6 instance:ShelfHeight " +cabinet6.shelfHeight);
		System.out.println("this is cabinet6 instance:shelfwidth " +cabinet6.shelfWidth);
		System.out.println("this is cabinet6 instance:ShelfDepth " +cabinet6.shelfDepth);
		System.out.println("this is cabinet6 instance:weight " +cabinet6.weight);
		System.out.println("this is cabinet6 instance:material " +cabinet6.material);
		System.out.println("this is cabinet6 instance:color " +cabinet6.color);
		System.out.println("this is cabinet6 instance:lockBrand " +cabinet6.lockBrand);


		cabinet7.shelves= 15;
		cabinet7.thickness = 18.7;
		cabinet7.doorHeight= 44.3;
		cabinet7.doorWidth = 29.8;
		cabinet7.drawers = 12;
		cabinet7.shelfHeight= 52;
		cabinet7.shelfWidth= 36;
		cabinet7.shelfDepth= 22;
		cabinet7.weight = 28.4;
		cabinet7.lockBrand= "Aru";

		System.out.println("this is cabinet7 instance:height " +cabinet7.height);
		System.out.println("this is cabinet7 instance:width " +cabinet7.width);
		System.out.println("this is cabinet7 instance:depth " +cabinet7.depth);
		System.out.println("this is cabinet7 instance:shelves " +cabinet7.shelves);
		System.out.println("this is cabinet7 instance:thickness " +cabinet7.thickness);
		System.out.println("this is cabinet7 instance:doorHeight " +cabinet7.doorHeight);
		System.out.println("this is cabinet7 instance:doorWidth " +cabinet7.doorWidth);
		System.out.println("this is cabinet7 instance:drawers " +cabinet7.drawers);
		System.out.println("this is cabinet7 instance:ShelfHeight " +cabinet7.shelfHeight);
		System.out.println("this is cabinet7 instance:shelfwidth " +cabinet7.shelfWidth);
		System.out.println("this is cabinet7 instance:ShelfDepth " +cabinet7.shelfDepth);
		System.out.println("this is cabinet7 instance:weight " +cabinet7.weight);
		System.out.println("this is cabinet7 instance:material " +cabinet7.material);
		System.out.println("this is cabinet7 instance:color " +cabinet7.color);
		System.out.println("this is cabinet7 instance:lockBrand " +cabinet7.lockBrand);


		
		cabinet8.shelves= 60;
		cabinet8.thickness = 25.0;
		cabinet8.doorHeight= 70.2;
		cabinet8.doorWidth = 45.5;
		cabinet8.drawers = 35;
		cabinet8.shelfHeight= 80;
		cabinet8.shelfWidth= 55;
		cabinet8.shelfDepth= 40;
		cabinet8.weight = 60.0;
		cabinet8.lockBrand= "KIARA";

		System.out.println("this is cabinet8 instance:height " +cabinet8.height);
		System.out.println("this is cabinet8 instance:width " +cabinet8.width);
		System.out.println("this is cabinet8 instance:depth " +cabinet8.depth);
		System.out.println("this is cabinet8 instance:shelves " +cabinet8.shelves);
		System.out.println("this is cabinet8 instance:thickness " +cabinet8.thickness);
		System.out.println("this is cabinet8 instance:doorHeight " +cabinet8.doorHeight);
		System.out.println("this is cabinet8 instance:doorWidth " +cabinet8.doorWidth);
		System.out.println("this is cabinet8 instance:drawers " +cabinet8.drawers);
		System.out.println("this is cabinet8 instance:ShelfHeight " +cabinet8.shelfHeight);
		System.out.println("this is cabinet8 instance:shelfwidth " +cabinet8.shelfWidth);
		System.out.println("this is cabinet8 instance:ShelfDepth " +cabinet8.shelfDepth);
		System.out.println("this is cabinet8 instance:weight " +cabinet8.weight);
		System.out.println("this is cabinet8 instance:material " +cabinet8.material);
		System.out.println("this is cabinet8 instance:color " +cabinet8.color);
		System.out.println("this is cabinet8 instance:lockBrand " +cabinet8.lockBrand);


		
		cabinet9.shelves= 22;
		cabinet9.thickness = 19.9;
		cabinet9.doorHeight= 48.6;
		cabinet9.doorWidth = 33.3;
		cabinet9.drawers = 16;
		cabinet9.shelfHeight= 58;
		cabinet9.shelfWidth= 40;
		cabinet9.shelfDepth= 25;
		cabinet9.weight = 30.2;
		cabinet9.lockBrand= "Mac";

		System.out.println("this is cabinet9 instance:height " +cabinet9.height);
		System.out.println("this is cabinet9 instance:width " +cabinet9.width);
		System.out.println("this is cabinet9 instance:depth " +cabinet9.depth);
		System.out.println("this is cabinet9 instance:shelves " +cabinet9.shelves);
		System.out.println("this is cabinet9 instance:thickness " +cabinet9.thickness);
		System.out.println("this is cabinet9 instance:doorHeight " +cabinet9.doorHeight);
		System.out.println("this is cabinet9 instance:doorWidth " +cabinet9.doorWidth);
		System.out.println("this is cabinet9 instance:drawers " +cabinet9.drawers);
		System.out.println("this is cabinet9 instance:ShelfHeight " +cabinet9.shelfHeight);
		System.out.println("this is cabinet9 instance:shelfwidth " +cabinet9.shelfWidth);
		System.out.println("this is cabinet9 instance:ShelfDepth " +cabinet9.shelfDepth);
		System.out.println("this is cabinet9 instance:weight " +cabinet9.weight);
		System.out.println("this is cabinet9 instance:material " +cabinet9.material);
		System.out.println("this is cabinet9 instance:color " +cabinet9.color);
		System.out.println("this is cabinet9 instance:lockBrand " +cabinet9.lockBrand);


		
		cabinet10.shelves= 75;
		cabinet10.thickness = 28.8;
		cabinet10.doorHeight= 82.0;
		cabinet10.doorWidth = 50.0;
		cabinet10.drawers = 45;
		cabinet10.shelfHeight= 90;
		cabinet10.shelfWidth= 65;
		cabinet10.shelfDepth= 48;
		cabinet10.weight = 72.3;
		cabinet10.lockBrand= "Deep";

		System.out.println("this is cabinet10 instance:height " +cabinet10.height);
		System.out.println("this is cabinet10instance:width " +cabinet10.width);
		System.out.println("this is cabinet10instance:depth " +cabinet10.depth);
		System.out.println("this is cabinet10 instance:shelves " +cabinet10.shelves);
		System.out.println("this is cabinet10 instance:thickness " +cabinet10.thickness);
		System.out.println("this is cabinet10 instance:doorHeight " +cabinet10.doorHeight);
		System.out.println("this is cabinet10 instance:doorWidth " +cabinet10.doorWidth);
		System.out.println("this is cabinet10 instance:drawers " +cabinet10.drawers);
		System.out.println("this is cabinet10 instance:ShelfHeight " +cabinet10.shelfHeight);
		System.out.println("this is cabinet10 instance:shelfwidth " +cabinet10.shelfWidth);
		System.out.println("this is cabinet10 instance:ShelfDepth " +cabinet10.shelfDepth);
		System.out.println("this is cabinet10 instance:weight " +cabinet10.weight);
		System.out.println("this is cabinet10 instance:material " +cabinet10.material);
		System.out.println("this is cabinet10 instance:color " +cabinet10.color);
		System.out.println("this is cabinet10 instance:lockBrand " +cabinet10.lockBrand);
		
		cabinet6=cabinet7;
		System.out.println("this is cabinet6 instance:height " +cabinet6.height);
		System.out.println("this is cabinet6 instance:width " +cabinet6.width);
		System.out.println("this is cabinet6 instance:depth " +cabinet6.depth);
		System.out.println("this is cabinet6 instance:shelves " +cabinet6.shelves);
		System.out.println("this is cabinet6 instance:thickness " +cabinet6.thickness);
		System.out.println("this is cabinet6 instance:doorHeight " +cabinet6.doorHeight);
		System.out.println("this is cabinet6 instance:doorWidth " +cabinet6.doorWidth);
		System.out.println("this is cabinet6 instance:drawers " +cabinet6.drawers);
		System.out.println("this is cabinet6 instance:ShelfHeight " +cabinet6.shelfHeight);
		System.out.println("this is cabinet6 instance:shelfwidth " +cabinet6.shelfWidth);
		System.out.println("this is cabinet6 instance:ShelfDepth " +cabinet6.shelfDepth);
		System.out.println("this is cabinet6 instance:weight " +cabinet6.weight);
		System.out.println("this is cabinet6 instance:material " +cabinet6.material);
		System.out.println("this is cabinet6 instance:color " +cabinet6.color);
		System.out.println("this is cabinet6 instance:lockBrand " +cabinet6.lockBrand);
			}
		}