class ControllerRunner {
	public static void main(String... values) {
		Controller controller1 = new Controller();
		Controller controller2 = new Controller();
		Controller controller3 = new Controller();
		Controller controller4 = new Controller();
		Controller controller5 = new Controller();
		Controller controller6 = new Controller();
		Controller controller7 = new Controller();
		Controller controller8 = new Controller();
		Controller controller9 = new Controller();
		Controller controller10 = new Controller();

		controller1.brand = "Sony";
		controller1.buttons = 14;
		controller1.connectivity = "Wireless";
		controller1.type = "Gamepad";
		controller1.compatibility = "PS5";
		controller1.batteryType = "LiPo";
		controller1.batteryLife = 12;
		controller1.triggerType = "Adaptive";
		controller1.vibration = "HapticFeedback";
		controller1.layout = "Standard";

		System.out.println("this is controller1 instance:length " + controller1.length);
		System.out.println("this is controller1 instance:width " + controller1.width);
		System.out.println("this is controller1 instance:height " + controller1.height);
		System.out.println("this is controller1 instance:color " + controller1.color);
		System.out.println("this is controller1 instance:material " + controller1.material);
		System.out.println("this is controller1 instance:brand " + controller1.brand);
		System.out.println("this is controller1 instance:buttons " + controller1.buttons);
		System.out.println("this is controller1 instance:connectivity " + controller1.connectivity);
		System.out.println("this is controller1 instance:type " + controller1.type);
		System.out.println("this is controller1 instance:compatibility " + controller1.compatibility);
		System.out.println("this is controller1 instance:batteryType " + controller1.batteryType);
		System.out.println("this is controller1 instance:batteryLife " + controller1.batteryLife);
		System.out.println("this is controller1 instance:triggerType " + controller1.triggerType);
		System.out.println("this is controller1 instance:vibration " + controller1.vibration);
		System.out.println("this is controller1 instance:layout " + controller1.layout);

		controller2.brand = "Microsoft";
		controller2.buttons = 12;
		controller2.connectivity = "Wireless";
		controller2.type = "Gamepad";
		controller2.compatibility = "Xbox";
		controller2.batteryType = "AA";
		controller2.batteryLife = 40;
		controller2.triggerType = "Impulse";
		controller2.vibration = "DualRumble";
		controller2.layout = "Asymmetric";

		System.out.println("this is controller2 instance:length " + controller2.length);
		System.out.println("this is controller2 instance:width " + controller2.width);
		System.out.println("this is controller2 instance:height " + controller2.height);
		System.out.println("this is controller2 instance:color " + controller2.color);
		System.out.println("this is controller2 instance:material " + controller2.material);
		System.out.println("this is controller2 instance:brand " + controller2.brand);
		System.out.println("this is controller2 instance:buttons " + controller2.buttons);
		System.out.println("this is controller2 instance:connectivity " + controller2.connectivity);
		System.out.println("this is controller2 instance:type " + controller2.type);
		System.out.println("this is controller2 instance:compatibility " + controller2.compatibility);
		System.out.println("this is controller2 instance:batteryType " + controller2.batteryType);
		System.out.println("this is controller2 instance:batteryLife " + controller2.batteryLife);
		System.out.println("this is controller2 instance:triggerType " + controller2.triggerType);
		System.out.println("this is controller2 instance:vibration " + controller2.vibration);
		System.out.println("this is controller2 instance:layout " + controller2.layout);

		controller3.brand = "Nintendo";
		controller3.buttons = 16;
		controller3.connectivity = "Wireless";
		controller3.type = "Gamepad";
		controller3.compatibility = "Switch";
		controller3.batteryType = "LiPo";
		controller3.batteryLife = 20;
		controller3.triggerType = "Standard";
		controller3.vibration = "HDRumble";
		controller3.layout = "Symmetric";

		System.out.println("this is controller3 instance:length " + controller3.length);
		System.out.println("this is controller3 instance:width " + controller3.width);
		System.out.println("this is controller3 instance:height " + controller3.height);
		System.out.println("this is controller3 instance:color " + controller3.color);
		System.out.println("this is controller3 instance:material " + controller3.material);
		System.out.println("this is controller3 instance:brand " + controller3.brand);
		System.out.println("this is controller3 instance:buttons " + controller3.buttons);
		System.out.println("this is controller3 instance:connectivity " + controller3.connectivity);
		System.out.println("this is controller3 instance:type " + controller3.type);
		System.out.println("this is controller3 instance:compatibility " + controller3.compatibility);
		System.out.println("this is controller3 instance:batteryType " + controller3.batteryType);
		System.out.println("this is controller3 instance:batteryLife " + controller3.batteryLife);
		System.out.println("this is controller3 instance:triggerType " + controller3.triggerType);
		System.out.println("this is controller3 instance:vibration " + controller3.vibration);
		System.out.println("this is controller3 instance:layout " + controller3.layout);

		controller4.brand = "Logitech";
		controller4.buttons = 11;
		controller4.connectivity = "Wired";
		controller4.type = "Gamepad";
		controller4.compatibility = "PC";
		controller4.batteryType = "None";
		controller4.batteryLife = 0;
		controller4.triggerType = "Analog";
		controller4.vibration = "DualRumble";
		controller4.layout = "Symmetric";

		System.out.println("this is controller4 instance:length " + controller4.length);
		System.out.println("this is controller4 instance:width " + controller4.width);
		System.out.println("this is controller4 instance:height " + controller4.height);
		System.out.println("this is controller4 instance:color " + controller4.color);
		System.out.println("this is controller4 instance:material " + controller4.material);
		System.out.println("this is controller4 instance:brand " + controller4.brand);
		System.out.println("this is controller4 instance:buttons " + controller4.buttons);
		System.out.println("this is controller4 instance:connectivity " + controller4.connectivity);
		System.out.println("this is controller4 instance:type " + controller4.type);
		System.out.println("this is controller4 instance:compatibility " + controller4.compatibility);
		System.out.println("this is controller4 instance:batteryType " + controller4.batteryType);
		System.out.println("this is controller4 instance:batteryLife " + controller4.batteryLife);
		System.out.println("this is controller4 instance:triggerType " + controller4.triggerType);
		System.out.println("this is controller4 instance:vibration " + controller4.vibration);
		System.out.println("this is controller4 instance:layout " + controller4.layout);

		controller5.brand = "Razer";
		controller5.buttons = 13;
		controller5.connectivity = "Wireless";
		controller5.type = "Gamepad";
		controller5.compatibility = "PC";
		controller5.batteryType = "LiPo";
		controller5.batteryLife = 15;
		controller5.triggerType = "HairTrigger";
		controller5.vibration = "DualRumble";
		controller5.layout = "Asymmetric";

		System.out.println("this is controller5 instance:length " + controller5.length);
		System.out.println("this is controller5 instance:width " + controller5.width);
		System.out.println("this is controller5 instance:height " + controller5.height);
		System.out.println("this is controller5 instance:color " + controller5.color);
		System.out.println("this is controller5 instance:material " + controller5.material);
		System.out.println("this is controller5 instance:brand " + controller5.brand);
		System.out.println("this is controller5 instance:buttons " + controller5.buttons);
		System.out.println("this is controller5 instance:connectivity " + controller5.connectivity);
		System.out.println("this is controller5 instance:type " + controller5.type);
		System.out.println("this is controller5 instance:compatibility " + controller5.compatibility);
		System.out.println("this is controller5 instance:batteryType " + controller5.batteryType);
		System.out.println("this is controller5 instance:batteryLife " + controller5.batteryLife);
		System.out.println("this is controller5 instance:triggerType " + controller5.triggerType);
		System.out.println("this is controller5 instance:vibration " + controller5.vibration);
		System.out.println("this is controller5 instance:layout " + controller5.layout);

		controller6.brand = "8BitDo";
		controller6.buttons = 12;
		controller6.connectivity = "Bluetooth";
		controller6.type = "Retro";
		controller6.compatibility = "PC";
		controller6.batteryType = "LiPo";
		controller6.batteryLife = 18;
		controller6.triggerType = "Standard";
		controller6.vibration = "SingleRumble";
		controller6.layout = "Symmetric";

		System.out.println("this is controller6 instance:length " + controller6.length);
		System.out.println("this is controller6 instance:width " + controller6.width);
		System.out.println("this is controller6 instance:height " + controller6.height);
		System.out.println("this is controller6 instance:color " + controller6.color);
		System.out.println("this is controller6 instance:material " + controller6.material);
		System.out.println("this is controller6 instance:brand " + controller6.brand);
		System.out.println("this is controller6 instance:buttons " + controller6.buttons);
		System.out.println("this is controller6 instance:connectivity " + controller6.connectivity);
		System.out.println("this is controller6 instance:type " + controller6.type);
		System.out.println("this is controller6 instance:compatibility " + controller6.compatibility);
		System.out.println("this is controller6 instance:batteryType " + controller6.batteryType);
		System.out.println("this is controller6 instance:batteryLife " + controller6.batteryLife);
		System.out.println("this is controller6 instance:triggerType " + controller6.triggerType);
		System.out.println("this is controller6 instance:vibration " + controller6.vibration);
		System.out.println("this is controller6 instance:layout " + controller6.layout);

		controller7.brand = "PowerA";
		controller7.buttons = 12;
		controller7.connectivity = "Wired";
		controller7.type = "Gamepad";
		controller7.compatibility = "Xbox";
		controller7.batteryType = "None";
		controller7.batteryLife = 0;
		controller7.triggerType = "Analog";
		controller7.vibration = "DualRumble";
		controller7.layout = "Asymmetric";

		System.out.println("this is controller7 instance:length " + controller7.length);
		System.out.println("this is controller7 instance:width " + controller7.width);
		System.out.println("this is controller7 instance:height " + controller7.height);
		System.out.println("this is controller7 instance:color " + controller7.color);
		System.out.println("this is controller7 instance:material " + controller7.material);
		System.out.println("this is controller7 instance:brand " + controller7.brand);
		System.out.println("this is controller7 instance:buttons " + controller7.buttons);
		System.out.println("this is controller7 instance:connectivity " + controller7.connectivity);
		System.out.println("this is controller7 instance:type " + controller7.type);
		System.out.println("this is controller7 instance:compatibility " + controller7.compatibility);
		System.out.println("this is controller7 instance:batteryType " + controller7.batteryType);
		System.out.println("this is controller7 instance:batteryLife " + controller7.batteryLife);
		System.out.println("this is controller7 instance:triggerType " + controller7.triggerType);
		System.out.println("this is controller7 instance:vibration " + controller7.vibration);
		System.out.println("this is controller7 instance:layout " + controller7.layout);

		controller8.brand = "Hori";
		controller8.buttons = 15;
		controller8.connectivity = "Wired";
		controller8.type = "FightingStick";
		controller8.compatibility = "PS5";
		controller8.batteryType = "None";
		controller8.batteryLife = 0;
		controller8.triggerType = "Arcade";
		controller8.vibration = "None";
		controller8.layout = "Arcade";

		System.out.println("this is controller8 instance:length " + controller8.length);
		System.out.println("this is controller8 instance:width " + controller8.width);
		System.out.println("this is controller8 instance:height " + controller8.height);
		System.out.println("this is controller8 instance:color " + controller8.color);
		System.out.println("this is controller8 instance:material " + controller8.material);
		System.out.println("this is controller8 instance:brand " + controller8.brand);
		System.out.println("this is controller8 instance:buttons " + controller8.buttons);
		System.out.println("this is controller8 instance:connectivity " + controller8.connectivity);
		System.out.println("this is controller8 instance:type " + controller8.type);
		System.out.println("this is controller8 instance:compatibility " + controller8.compatibility);
		System.out.println("this is controller8 instance:batteryType " + controller8.batteryType);
		System.out.println("this is controller8 instance:batteryLife " + controller8.batteryLife);
		System.out.println("this is controller8 instance:triggerType " + controller8.triggerType);
		System.out.println("this is controller8 instance:vibration " + controller8.vibration);
		System.out.println("this is controller8 instance:layout " + controller8.layout);

		controller9.brand = "Thrustmaster";
		controller9.buttons = 10;
		controller9.connectivity = "Wired";
		controller9.type = "RacingWheel";
		controller9.compatibility = "PC";
		controller9.batteryType = "None";
		controller9.batteryLife = 0;
		controller9.triggerType = "Pedal";
		controller9.vibration = "ForceFeedback";
		controller9.layout = "Racing";

		System.out.println("this is controller9 instance:length " + controller9.length);
		System.out.println("this is controller9 instance:width " + controller9.width);
		System.out.println("this is controller9 instance:height " + controller9.height);
		System.out.println("this is controller9 instance:color " + controller9.color);
		System.out.println("this is controller9 instance:material " + controller9.material);
		System.out.println("this is controller9 instance:brand " + controller9.brand);
		System.out.println("this is controller9 instance:buttons " + controller9.buttons);
		System.out.println("this is controller9 instance:connectivity " + controller9.connectivity);
		System.out.println("this is controller9 instance:type " + controller9.type);
		System.out.println("this is controller9 instance:compatibility " + controller9.compatibility);
		System.out.println("this is controller9 instance:batteryType " + controller9.batteryType);
		System.out.println("this is controller9 instance:batteryLife " + controller9.batteryLife);
		System.out.println("this is controller9 instance:triggerType " + controller9.triggerType);
		System.out.println("this is controller9 instance:vibration " + controller9.vibration);
		System.out.println("this is controller9 instance:layout " + controller9.layout);

		controller10.brand = "Scuf";
		controller10.buttons = 16;
		controller10.connectivity = "Wireless";
		controller10.type = "ProGamepad";
		controller10.compatibility = "PS5";
		controller10.batteryType = "LiPo";
		controller10.batteryLife = 10;
		controller10.triggerType = "HairTrigger";
		controller10.vibration = "DualRumble";
		controller10.layout = "Symmetric";

		System.out.println("this is controller10 instance:length " + controller10.length);
		System.out.println("this is controller10 instance:width " + controller10.width);
		System.out.println("this is controller10 instance:height " + controller10.height);
		System.out.println("this is controller10 instance:color " + controller10.color);
		System.out.println("this is controller10 instance:material " + controller10.material);
		System.out.println("this is controller10 instance:brand " + controller10.brand);
		System.out.println("this is controller10 instance:buttons " + controller10.buttons);
		System.out.println("this is controller10 instance:connectivity " + controller10.connectivity);
		System.out.println("this is controller10 instance:type " + controller10.type);
		System.out.println("this is controller10 instance:compatibility " + controller10.compatibility);
		System.out.println("this is controller10 instance:batteryType " + controller10.batteryType);
		System.out.println("this is controller10 instance:batteryLife " + controller10.batteryLife);
		System.out.println("this is controller10 instance:triggerType " + controller10.triggerType);
		System.out.println("this is controller10 instance:vibration " + controller10.vibration);
		System.out.println("this is controller10 instance:layout " + controller10.layout);

		controller6 = controller7;
		System.out.println("this is controller6 instance:length " + controller6.length);
		System.out.println("this is controller6 instance:width " + controller6.width);
		System.out.println("this is controller6 instance:height " + controller6.height);
		System.out.println("this is controller6 instance:color " + controller6.color);
		System.out.println("this is controller6 instance:material " + controller6.material);
		System.out.println("this is controller6 instance:brand " + controller6.brand);
		System.out.println("this is controller6 instance:buttons " + controller6.buttons);
		System.out.println("this is controller6 instance:connectivity " + controller6.connectivity);
		System.out.println("this is controller6 instance:type " + controller6.type);
		System.out.println("this is controller6 instance:compatibility " + controller6.compatibility);
		System.out.println("this is controller6 instance:batteryType " + controller6.batteryType);
		System.out.println("this is controller6 instance:batteryLife " + controller6.batteryLife);
		System.out.println("this is controller6 instance:triggerType " + controller6.triggerType);
		System.out.println("this is controller6 instance:vibration " + controller6.vibration);
		System.out.println("this is controller6 instance:layout " + controller6.layout);
	}
}