class EthernetRunner {
	public static void main(String... values) {
		Ethernet ethernet1 = new Ethernet();
		Ethernet ethernet2 = new Ethernet();
		Ethernet ethernet3 = new Ethernet();
		Ethernet ethernet4 = new Ethernet();
		Ethernet ethernet5 = new Ethernet();
		Ethernet ethernet6 = new Ethernet();
		Ethernet ethernet7 = new Ethernet();
		Ethernet ethernet8 = new Ethernet();
		Ethernet ethernet9 = new Ethernet();
		Ethernet ethernet10 = new Ethernet();

		ethernet1.brand = "Belkin";
		ethernet1.category = "Cat6";
		ethernet1.speedMbps = 1000;
		ethernet1.connector = "RJ45";
		ethernet1.shielding = "UTP";
		ethernet1.cableLength = 1.5;
		ethernet1.standard = "IEEE802.3";
		ethernet1.bandwidth = "250MHz";
		ethernet1.compatibility = "Windows";
		ethernet1.application = "Office";

		System.out.println("this is ethernet1 instance:length " + ethernet1.length);
		System.out.println("this is ethernet1 instance:width " + ethernet1.width);
		System.out.println("this is ethernet1 instance:height " + ethernet1.height);
		System.out.println("this is ethernet1 instance:color " + ethernet1.color);
		System.out.println("this is ethernet1 instance:material " + ethernet1.material);
		System.out.println("this is ethernet1 instance:brand " + ethernet1.brand);
		System.out.println("this is ethernet1 instance:category " + ethernet1.category);
		System.out.println("this is ethernet1 instance:speedMbps " + ethernet1.speedMbps);
		System.out.println("this is ethernet1 instance:connector " + ethernet1.connector);
		System.out.println("this is ethernet1 instance:shielding " + ethernet1.shielding);
		System.out.println("this is ethernet1 instance:cableLength " + ethernet1.cableLength);
		System.out.println("this is ethernet1 instance:standard " + ethernet1.standard);
		System.out.println("this is ethernet1 instance:bandwidth " + ethernet1.bandwidth);
		System.out.println("this is ethernet1 instance:compatibility " + ethernet1.compatibility);
		System.out.println("this is ethernet1 instance:application " + ethernet1.application);

		ethernet2.brand = "AmazonBasics";
		ethernet2.category = "Cat7";
		ethernet2.speedMbps = 10000;
		ethernet2.connector = "RJ45";
		ethernet2.shielding = "STP";
		ethernet2.cableLength = 3.0;
		ethernet2.standard = "IEEE802.3";
		ethernet2.bandwidth = "600MHz";
		ethernet2.compatibility = "Linux";
		ethernet2.application = "DataCenter";

		System.out.println("this is ethernet2 instance:length " + ethernet2.length);
		System.out.println("this is ethernet2 instance:width " + ethernet2.width);
		System.out.println("this is ethernet2 instance:height " + ethernet2.height);
		System.out.println("this is ethernet2 instance:color " + ethernet2.color);
		System.out.println("this is ethernet2 instance:material " + ethernet2.material);
		System.out.println("this is ethernet2 instance:brand " + ethernet2.brand);
		System.out.println("this is ethernet2 instance:category " + ethernet2.category);
		System.out.println("this is ethernet2 instance:speedMbps " + ethernet2.speedMbps);
		System.out.println("this is ethernet2 instance:connector " + ethernet2.connector);
		System.out.println("this is ethernet2 instance:shielding " + ethernet2.shielding);
		System.out.println("this is ethernet2 instance:cableLength " + ethernet2.cableLength);
		System.out.println("this is ethernet2 instance:standard " + ethernet2.standard);
		System.out.println("this is ethernet2 instance:bandwidth " + ethernet2.bandwidth);
		System.out.println("this is ethernet2 instance:compatibility " + ethernet2.compatibility);
		System.out.println("this is ethernet2 instance:application " + ethernet2.application);

		ethernet3.brand = "TP-Link";
		ethernet3.category = "Cat5e";
		ethernet3.speedMbps = 100;
		ethernet3.connector = "RJ45";
		ethernet3.shielding = "UTP";
		ethernet3.cableLength = 5.0;
		ethernet3.standard = "IEEE802.3";
		ethernet3.bandwidth = "100MHz";
		ethernet3.compatibility = "Windows";
		ethernet3.application = "Home";

		System.out.println("this is ethernet3 instance:length " + ethernet3.length);
		System.out.println("this is ethernet3 instance:width " + ethernet3.width);
		System.out.println("this is ethernet3 instance:height " + ethernet3.height);
		System.out.println("this is ethernet3 instance:color " + ethernet3.color);
		System.out.println("this is ethernet3 instance:material " + ethernet3.material);
		System.out.println("this is ethernet3 instance:brand " + ethernet3.brand);
		System.out.println("this is ethernet3 instance:category " + ethernet3.category);
		System.out.println("this is ethernet3 instance:speedMbps " + ethernet3.speedMbps);
		System.out.println("this is ethernet3 instance:connector " + ethernet3.connector);
		System.out.println("this is ethernet3 instance:shielding " + ethernet3.shielding);
		System.out.println("this is ethernet3 instance:cableLength " + ethernet3.cableLength);
		System.out.println("this is ethernet3 instance:standard " + ethernet3.standard);
		System.out.println("this is ethernet3 instance:bandwidth " + ethernet3.bandwidth);
		System.out.println("this is ethernet3 instance:compatibility " + ethernet3.compatibility);
		System.out.println("this is ethernet3 instance:application " + ethernet3.application);

		ethernet4.brand = "Ugreen";
		ethernet4.category = "Cat8";
		ethernet4.speedMbps = 40000;
		ethernet4.connector = "RJ45";
		ethernet4.shielding = "SFTP";
		ethernet4.cableLength = 2.0;
		ethernet4.standard = "IEEE802.3";
		ethernet4.bandwidth = "2000MHz";
		ethernet4.compatibility = "Mac";
		ethernet4.application = "Gaming";

		System.out.println("this is ethernet4 instance:length " + ethernet4.length);
		System.out.println("this is ethernet4 instance:width " + ethernet4.width);
		System.out.println("this is ethernet4 instance:height " + ethernet4.height);
		System.out.println("this is ethernet4 instance:color " + ethernet4.color);
		System.out.println("this is ethernet4 instance:material " + ethernet4.material);
		System.out.println("this is ethernet4 instance:brand " + ethernet4.brand);
		System.out.println("this is ethernet4 instance:category " + ethernet4.category);
		System.out.println("this is ethernet4 instance:speedMbps " + ethernet4.speedMbps);
		System.out.println("this is ethernet4 instance:connector " + ethernet4.connector);
		System.out.println("this is ethernet4 instance:shielding " + ethernet4.shielding);
		System.out.println("this is ethernet4 instance:cableLength " + ethernet4.cableLength);
		System.out.println("this is ethernet4 instance:standard " + ethernet4.standard);
		System.out.println("this is ethernet4 instance:bandwidth " + ethernet4.bandwidth);
		System.out.println("this is ethernet4 instance:compatibility " + ethernet4.compatibility);
		System.out.println("this is ethernet4 instance:application " + ethernet4.application);

		ethernet5.brand = "Netgear";
		ethernet5.category = "Cat6a";
		ethernet5.speedMbps = 10000;
		ethernet5.connector = "RJ45";
		ethernet5.shielding = "UTP";
		ethernet5.cableLength = 10.0;
		ethernet5.standard = "IEEE802.3";
		ethernet5.bandwidth = "500MHz";
		ethernet5.compatibility = "Linux";
		ethernet5.application = "Enterprise";

		System.out.println("this is ethernet5 instance:length " + ethernet5.length);
		System.out.println("this is ethernet5 instance:width " + ethernet5.width);
		System.out.println("this is ethernet5 instance:height " + ethernet5.height);
		System.out.println("this is ethernet5 instance:color " + ethernet5.color);
		System.out.println("this is ethernet5 instance:material " + ethernet5.material);
		System.out.println("this is ethernet5 instance:brand " + ethernet5.brand);
		System.out.println("this is ethernet5 instance:category " + ethernet5.category);
		System.out.println("this is ethernet5 instance:speedMbps " + ethernet5.speedMbps);
		System.out.println("this is ethernet5 instance:connector " + ethernet5.connector);
		System.out.println("this is ethernet5 instance:shielding " + ethernet5.shielding);
		System.out.println("this is ethernet5 instance:cableLength " + ethernet5.cableLength);
		System.out.println("this is ethernet5 instance:standard " + ethernet5.standard);
		System.out.println("this is ethernet5 instance:bandwidth " + ethernet5.bandwidth);
		System.out.println("this is ethernet5 instance:compatibility " + ethernet5.compatibility);
		System.out.println("this is ethernet5 instance:application " + ethernet5.application);

		ethernet6.brand = "CableMatters";
		ethernet6.category = "Cat6";
		ethernet6.speedMbps = 1000;
		ethernet6.connector = "RJ45";
		ethernet6.shielding = "UTP";
		ethernet6.cableLength = 7.5;
		ethernet6.standard = "IEEE802.3";
		ethernet6.bandwidth = "250MHz";
		ethernet6.compatibility = "Windows";
		ethernet6.application = "Home";

		System.out.println("this is ethernet6 instance:length " + ethernet6.length);
		System.out.println("this is ethernet6 instance:width " + ethernet6.width);
		System.out.println("this is ethernet6 instance:height " + ethernet6.height);
		System.out.println("this is ethernet6 instance:color " + ethernet6.color);
		System.out.println("this is ethernet6 instance:material " + ethernet6.material);
		System.out.println("this is ethernet6 instance:brand " + ethernet6.brand);
		System.out.println("this is ethernet6 instance:category " + ethernet6.category);
		System.out.println("this is ethernet6 instance:speedMbps " + ethernet6.speedMbps);
		System.out.println("this is ethernet6 instance:connector " + ethernet6.connector);
		System.out.println("this is ethernet6 instance:shielding " + ethernet6.shielding);
		System.out.println("this is ethernet6 instance:cableLength " + ethernet6.cableLength);
		System.out.println("this is ethernet6 instance:standard " + ethernet6.standard);
		System.out.println("this is ethernet6 instance:bandwidth " + ethernet6.bandwidth);
		System.out.println("this is ethernet6 instance:compatibility " + ethernet6.compatibility);
		System.out.println("this is ethernet6 instance:application " + ethernet6.application);

		ethernet7.brand = "Monoprice";
		ethernet7.category = "Cat7";
		ethernet7.speedMbps = 10000;
		ethernet7.connector = "RJ45";
		ethernet7.shielding = "STP";
		ethernet7.cableLength = 15.0;
		ethernet7.standard = "IEEE802.3";
		ethernet7.bandwidth = "600MHz";
		ethernet7.compatibility = "Mac";
		ethernet7.application = "Office";

		System.out.println("this is ethernet7 instance:length " + ethernet7.length);
		System.out.println("this is ethernet7 instance:width " + ethernet7.width);
		System.out.println("this is ethernet7 instance:height " + ethernet7.height);
		System.out.println("this is ethernet7 instance:color " + ethernet7.color);
		System.out.println("this is ethernet7 instance:material " + ethernet7.material);
		System.out.println("this is ethernet7 instance:brand " + ethernet7.brand);
		System.out.println("this is ethernet7 instance:category " + ethernet7.category);
		System.out.println("this is ethernet7 instance:speedMbps " + ethernet7.speedMbps);
		System.out.println("this is ethernet7 instance:connector " + ethernet7.connector);
		System.out.println("this is ethernet7 instance:shielding " + ethernet7.shielding);
		System.out.println("this is ethernet7 instance:cableLength " + ethernet7.cableLength);
		System.out.println("this is ethernet7 instance:standard " + ethernet7.standard);
		System.out.println("this is ethernet7 instance:bandwidth " + ethernet7.bandwidth);
		System.out.println("this is ethernet7 instance:compatibility " + ethernet7.compatibility);
		System.out.println("this is ethernet7 instance:application " + ethernet7.application);

		ethernet8.brand = "Jadaol";
		ethernet8.category = "Cat8";
		ethernet8.speedMbps = 40000;
		ethernet8.connector = "RJ45";
		ethernet8.shielding = "SFTP";
		ethernet8.cableLength = 30.0;
		ethernet8.standard = "IEEE802.3";
		ethernet8.bandwidth = "2000MHz";
		ethernet8.compatibility = "Windows";
		ethernet8.application = "DataCenter";

		System.out.println("this is ethernet8 instance:length " + ethernet8.length);
		System.out.println("this is ethernet8 instance:width " + ethernet8.width);
		System.out.println("this is ethernet8 instance:height " + ethernet8.height);
		System.out.println("this is ethernet8 instance:color " + ethernet8.color);
		System.out.println("this is ethernet8 instance:material " + ethernet8.material);
		System.out.println("this is ethernet8 instance:brand " + ethernet8.brand);
		System.out.println("this is ethernet8 instance:category " + ethernet8.category);
		System.out.println("this is ethernet8 instance:speedMbps " + ethernet8.speedMbps);
		System.out.println("this is ethernet8 instance:connector " + ethernet8.connector);
		System.out.println("this is ethernet8 instance:shielding " + ethernet8.shielding);
		System.out.println("this is ethernet8 instance:cableLength " + ethernet8.cableLength);
		System.out.println("this is ethernet8 instance:standard " + ethernet8.standard);
		System.out.println("this is ethernet8 instance:bandwidth " + ethernet8.bandwidth);
		System.out.println("this is ethernet8 instance:compatibility " + ethernet8.compatibility);
		System.out.println("this is ethernet8 instance:application " + ethernet8.application);

		ethernet9.brand = "DLink";
		ethernet9.category = "Cat5e";
		ethernet9.speedMbps = 1000;
		ethernet9.connector = "RJ45";
		ethernet9.shielding = "UTP";
		ethernet9.cableLength = 20.0;
		ethernet9.standard = "IEEE802.3";
		ethernet9.bandwidth = "100MHz";
		ethernet9.compatibility = "Linux";
		ethernet9.application = "Home";

		System.out.println("this is ethernet9 instance:length " + ethernet9.length);
		System.out.println("this is ethernet9 instance:width " + ethernet9.width);
		System.out.println("this is ethernet9 instance:height " + ethernet9.height);
		System.out.println("this is ethernet9 instance:color " + ethernet9.color);
		System.out.println("this is ethernet9 instance:material " + ethernet9.material);
		System.out.println("this is ethernet9 instance:brand " + ethernet9.brand);
		System.out.println("this is ethernet9 instance:category " + ethernet9.category);
		System.out.println("this is ethernet9 instance:speedMbps " + ethernet9.speedMbps);
		System.out.println("this is ethernet9 instance:connector " + ethernet9.connector);
		System.out.println("this is ethernet9 instance:shielding " + ethernet9.shielding);
		System.out.println("this is ethernet9 instance:cableLength " + ethernet9.cableLength);
		System.out.println("this is ethernet9 instance:standard " + ethernet9.standard);
		System.out.println("this is ethernet9 instance:bandwidth " + ethernet9.bandwidth);
		System.out.println("this is ethernet9 instance:compatibility " + ethernet9.compatibility);
		System.out.println("this is ethernet9 instance:application " + ethernet9.application);

		ethernet10.brand = "Cisco";
		ethernet10.category = "Cat6a";
		ethernet10.speedMbps = 10000;
		ethernet10.connector = "RJ45";
		ethernet10.shielding = "STP";
		ethernet10.cableLength = 50.0;
		ethernet10.standard = "IEEE802.3";
		ethernet10.bandwidth = "500MHz";
		ethernet10.compatibility = "Windows";
		ethernet10.application = "Enterprise";

		System.out.println("this is ethernet10 instance:length " + ethernet10.length);
		System.out.println("this is ethernet10 instance:width " + ethernet10.width);
		System.out.println("this is ethernet10 instance:height " + ethernet10.height);
		System.out.println("this is ethernet10 instance:color " + ethernet10.color);
		System.out.println("this is ethernet10 instance:material " + ethernet10.material);
		System.out.println("this is ethernet10 instance:brand " + ethernet10.brand);
		System.out.println("this is ethernet10 instance:category " + ethernet10.category);
		System.out.println("this is ethernet10 instance:speedMbps " + ethernet10.speedMbps);
		System.out.println("this is ethernet10 instance:connector " + ethernet10.connector);
		System.out.println("this is ethernet10 instance:shielding " + ethernet10.shielding);
		System.out.println("this is ethernet10 instance:cableLength " + ethernet10.cableLength);
		System.out.println("this is ethernet10 instance:standard " + ethernet10.standard);
		System.out.println("this is ethernet10 instance:bandwidth " + ethernet10.bandwidth);
		System.out.println("this is ethernet10 instance:compatibility " + ethernet10.compatibility);
		System.out.println("this is ethernet10 instance:application " + ethernet10.application);

		ethernet6 = ethernet7;
		System.out.println("this is ethernet6 instance:length " + ethernet6.length);
		System.out.println("this is ethernet6 instance:width " + ethernet6.width);
		System.out.println("this is ethernet6 instance:height " + ethernet6.height);
		System.out.println("this is ethernet6 instance:color " + ethernet6.color);
		System.out.println("this is ethernet6 instance:material " + ethernet6.material);
		System.out.println("this is ethernet6 instance:brand " + ethernet6.brand);
		System.out.println("this is ethernet6 instance:category " + ethernet6.category);
		System.out.println("this is ethernet6 instance:speedMbps " + ethernet6.speedMbps);
		System.out.println("this is ethernet6 instance:connector " + ethernet6.connector);
		System.out.println("this is ethernet6 instance:shielding " + ethernet6.shielding);
		System.out.println("this is ethernet6 instance:cableLength " + ethernet6.cableLength);
		System.out.println("this is ethernet6 instance:standard " + ethernet6.standard);
		System.out.println("this is ethernet6 instance:bandwidth " + ethernet6.bandwidth);
		System.out.println("this is ethernet6 instance:compatibility " + ethernet6.compatibility);
		System.out.println("this is ethernet6 instance:application " + ethernet6.application);
	}
}