class GraphicCardRunner {
	public static void main(String... values) {
		GraphicCard graphicCard1 = new GraphicCard();
		GraphicCard graphicCard2 = new GraphicCard();
		GraphicCard graphicCard3 = new GraphicCard();
		GraphicCard graphicCard4 = new GraphicCard();
		GraphicCard graphicCard5 = new GraphicCard();
		GraphicCard graphicCard6 = new GraphicCard();
		GraphicCard graphicCard7 = new GraphicCard();
		GraphicCard graphicCard8 = new GraphicCard();
		GraphicCard graphicCard9 = new GraphicCard();
		GraphicCard graphicCard10 = new GraphicCard();

		graphicCard1.brand = "Nvidia";
		graphicCard1.vram = 8;
		graphicCard1.gpuChip = "RTX3070";
		graphicCard1.busInterface = "PCIe4.0";
		graphicCard1.coreClock = 1500;
		graphicCard1.boostClock = 1730;
		graphicCard1.cooling = "DualFan";
		graphicCard1.powerConnector = "8Pin";
		graphicCard1.tdp = 220;
		graphicCard1.compatibility = "Windows";

		System.out.println("this is graphicCard1 instance:length " + graphicCard1.length);
		System.out.println("this is graphicCard1 instance:width " + graphicCard1.width);
		System.out.println("this is graphicCard1 instance:height " + graphicCard1.height);
		System.out.println("this is graphicCard1 instance:color " + graphicCard1.color);
		System.out.println("this is graphicCard1 instance:material " + graphicCard1.material);
		System.out.println("this is graphicCard1 instance:brand " + graphicCard1.brand);
		System.out.println("this is graphicCard1 instance:vram " + graphicCard1.vram);
		System.out.println("this is graphicCard1 instance:gpuChip " + graphicCard1.gpuChip);
		System.out.println("this is graphicCard1 instance:busInterface " + graphicCard1.busInterface);
		System.out.println("this is graphicCard1 instance:coreClock " + graphicCard1.coreClock);
		System.out.println("this is graphicCard1 instance:boostClock " + graphicCard1.boostClock);
		System.out.println("this is graphicCard1 instance:cooling " + graphicCard1.cooling);
		System.out.println("this is graphicCard1 instance:powerConnector " + graphicCard1.powerConnector);
		System.out.println("this is graphicCard1 instance:tdp " + graphicCard1.tdp);
		System.out.println("this is graphicCard1 instance:compatibility " + graphicCard1.compatibility);

		graphicCard2.brand = "AMD";
		graphicCard2.vram = 16;
		graphicCard2.gpuChip = "RX6800XT";
		graphicCard2.busInterface = "PCIe4.0";
		graphicCard2.coreClock = 1825;
		graphicCard2.boostClock = 2250;
		graphicCard2.cooling = "TripleFan";
		graphicCard2.powerConnector = "2x8Pin";
		graphicCard2.tdp = 300;
		graphicCard2.compatibility = "Windows";

		System.out.println("this is graphicCard2 instance:length " + graphicCard2.length);
		System.out.println("this is graphicCard2 instance:width " + graphicCard2.width);
		System.out.println("this is graphicCard2 instance:height " + graphicCard2.height);
		System.out.println("this is graphicCard2 instance:color " + graphicCard2.color);
		System.out.println("this is graphicCard2 instance:material " + graphicCard2.material);
		System.out.println("this is graphicCard2 instance:brand " + graphicCard2.brand);
		System.out.println("this is graphicCard2 instance:vram " + graphicCard2.vram);
		System.out.println("this is graphicCard2 instance:gpuChip " + graphicCard2.gpuChip);
		System.out.println("this is graphicCard2 instance:busInterface " + graphicCard2.busInterface);
		System.out.println("this is graphicCard2 instance:coreClock " + graphicCard2.coreClock);
		System.out.println("this is graphicCard2 instance:boostClock " + graphicCard2.boostClock);
		System.out.println("this is graphicCard2 instance:cooling " + graphicCard2.cooling);
		System.out.println("this is graphicCard2 instance:powerConnector " + graphicCard2.powerConnector);
		System.out.println("this is graphicCard2 instance:tdp " + graphicCard2.tdp);
		System.out.println("this is graphicCard2 instance:compatibility " + graphicCard2.compatibility);

		graphicCard3.brand = "Nvidia";
		graphicCard3.vram = 24;
		graphicCard3.gpuChip = "RTX3090";
		graphicCard3.busInterface = "PCIe4.0";
		graphicCard3.coreClock = 1395;
		graphicCard3.boostClock = 1695;
		graphicCard3.cooling = "TripleFan";
		graphicCard3.powerConnector = "3x8Pin";
		graphicCard3.tdp = 350;
		graphicCard3.compatibility = "Linux";

		System.out.println("this is graphicCard3 instance:length " + graphicCard3.length);
		System.out.println("this is graphicCard3 instance:width " + graphicCard3.width);
		System.out.println("this is graphicCard3 instance:height " + graphicCard3.height);
		System.out.println("this is graphicCard3 instance:color " + graphicCard3.color);
		System.out.println("this is graphicCard3 instance:material " + graphicCard3.material);
		System.out.println("this is graphicCard3 instance:brand " + graphicCard3.brand);
		System.out.println("this is graphicCard3 instance:vram " + graphicCard3.vram);
		System.out.println("this is graphicCard3 instance:gpuChip " + graphicCard3.gpuChip);
		System.out.println("this is graphicCard3 instance:busInterface " + graphicCard3.busInterface);
		System.out.println("this is graphicCard3 instance:coreClock " + graphicCard3.coreClock);
		System.out.println("this is graphicCard3 instance:boostClock " + graphicCard3.boostClock);
		System.out.println("this is graphicCard3 instance:cooling " + graphicCard3.cooling);
		System.out.println("this is graphicCard3 instance:powerConnector " + graphicCard3.powerConnector);
		System.out.println("this is graphicCard3 instance:tdp " + graphicCard3.tdp);
		System.out.println("this is graphicCard3 instance:compatibility " + graphicCard3.compatibility);

		graphicCard4.brand = "AMD";
		graphicCard4.vram = 4;
		graphicCard4.gpuChip = "RX570";
		graphicCard4.busInterface = "PCIe3.0";
		graphicCard4.coreClock = 1168;
		graphicCard4.boostClock = 1244;
		graphicCard4.cooling = "DualFan";
		graphicCard4.powerConnector = "8Pin";
		graphicCard4.tdp = 150;
		graphicCard4.compatibility = "Windows";

		System.out.println("this is graphicCard4 instance:length " + graphicCard4.length);
		System.out.println("this is graphicCard4 instance:width " + graphicCard4.width);
		System.out.println("this is graphicCard4 instance:height " + graphicCard4.height);
		System.out.println("this is graphicCard4 instance:color " + graphicCard4.color);
		System.out.println("this is graphicCard4 instance:material " + graphicCard4.material);
		System.out.println("this is graphicCard4 instance:brand " + graphicCard4.brand);
		System.out.println("this is graphicCard4 instance:vram " + graphicCard4.vram);
		System.out.println("this is graphicCard4 instance:gpuChip " + graphicCard4.gpuChip);
		System.out.println("this is graphicCard4 instance:busInterface " + graphicCard4.busInterface);
		System.out.println("this is graphicCard4 instance:coreClock " + graphicCard4.coreClock);
		System.out.println("this is graphicCard4 instance:boostClock " + graphicCard4.boostClock);
		System.out.println("this is graphicCard4 instance:cooling " + graphicCard4.cooling);
		System.out.println("this is graphicCard4 instance:powerConnector " + graphicCard4.powerConnector);
		System.out.println("this is graphicCard4 instance:tdp " + graphicCard4.tdp);
		System.out.println("this is graphicCard4 instance:compatibility " + graphicCard4.compatibility);

		graphicCard5.brand = "Nvidia";
		graphicCard5.vram = 6;
		graphicCard5.gpuChip = "GTX1660";
		graphicCard5.busInterface = "PCIe3.0";
		graphicCard5.coreClock = 1530;
		graphicCard5.boostClock = 1785;
		graphicCard5.cooling = "DualFan";
		graphicCard5.powerConnector = "8Pin";
		graphicCard5.tdp = 120;
		graphicCard5.compatibility = "Windows";

		System.out.println("this is graphicCard5 instance:length " + graphicCard5.length);
		System.out.println("this is graphicCard5 instance:width " + graphicCard5.width);
		System.out.println("this is graphicCard5 instance:height " + graphicCard5.height);
		System.out.println("this is graphicCard5 instance:color " + graphicCard5.color);
		System.out.println("this is graphicCard5 instance:material " + graphicCard5.material);
		System.out.println("this is graphicCard5 instance:brand " + graphicCard5.brand);
		System.out.println("this is graphicCard5 instance:vram " + graphicCard5.vram);
		System.out.println("this is graphicCard5 instance:gpuChip " + graphicCard5.gpuChip);
		System.out.println("this is graphicCard5 instance:busInterface " + graphicCard5.busInterface);
		System.out.println("this is graphicCard5 instance:coreClock " + graphicCard5.coreClock);
		System.out.println("this is graphicCard5 instance:boostClock " + graphicCard5.boostClock);
		System.out.println("this is graphicCard5 instance:cooling " + graphicCard5.cooling);
		System.out.println("this is graphicCard5 instance:powerConnector " + graphicCard5.powerConnector);
		System.out.println("this is graphicCard5 instance:tdp " + graphicCard5.tdp);
		System.out.println("this is graphicCard5 instance:compatibility " + graphicCard5.compatibility);

		graphicCard6.brand = "Intel";
		graphicCard6.vram = 8;
		graphicCard6.gpuChip = "ArcA770";
		graphicCard6.busInterface = "PCIe4.0";
		graphicCard6.coreClock = 2100;
		graphicCard6.boostClock = 2400;
		graphicCard6.cooling = "DualFan";
		graphicCard6.powerConnector = "8Pin";
		graphicCard6.tdp = 225;
		graphicCard6.compatibility = "Windows";

		System.out.println("this is graphicCard6 instance:length " + graphicCard6.length);
		System.out.println("this is graphicCard6 instance:width " + graphicCard6.width);
		System.out.println("this is graphicCard6 instance:height " + graphicCard6.height);
		System.out.println("this is graphicCard6 instance:color " + graphicCard6.color);
		System.out.println("this is graphicCard6 instance:material " + graphicCard6.material);
		System.out.println("this is graphicCard6 instance:brand " + graphicCard6.brand);
		System.out.println("this is graphicCard6 instance:vram " + graphicCard6.vram);
		System.out.println("this is graphicCard6 instance:gpuChip " + graphicCard6.gpuChip);
		System.out.println("this is graphicCard6 instance:busInterface " + graphicCard6.busInterface);
		System.out.println("this is graphicCard6 instance:coreClock " + graphicCard6.coreClock);
		System.out.println("this is graphicCard6 instance:boostClock " + graphicCard6.boostClock);
		System.out.println("this is graphicCard6 instance:cooling " + graphicCard6.cooling);
		System.out.println("this is graphicCard6 instance:powerConnector " + graphicCard6.powerConnector);
		System.out.println("this is graphicCard6 instance:tdp " + graphicCard6.tdp);
		System.out.println("this is graphicCard6 instance:compatibility " + graphicCard6.compatibility);

		graphicCard7.brand = "Nvidia";
		graphicCard7.vram = 12;
		graphicCard7.gpuChip = "RTX3060";
		graphicCard7.busInterface = "PCIe4.0";
		graphicCard7.coreClock = 1320;
		graphicCard7.boostClock = 1777;
		graphicCard7.cooling = "DualFan";
		graphicCard7.powerConnector = "12Pin";
		graphicCard7.tdp = 170;
		graphicCard7.compatibility = "Linux";

		System.out.println("this is graphicCard7 instance:length " + graphicCard7.length);
		System.out.println("this is graphicCard7 instance:width " + graphicCard7.width);
		System.out.println("this is graphicCard7 instance:height " + graphicCard7.height);
		System.out.println("this is graphicCard7 instance:color " + graphicCard7.color);
		System.out.println("this is graphicCard7 instance:material " + graphicCard7.material);
		System.out.println("this is graphicCard7 instance:brand " + graphicCard7.brand);
		System.out.println("this is graphicCard7 instance:vram " + graphicCard7.vram);
		System.out.println("this is graphicCard7 instance:gpuChip " + graphicCard7.gpuChip);
		System.out.println("this is graphicCard7 instance:busInterface " + graphicCard7.busInterface);
		System.out.println("this is graphicCard7 instance:coreClock " + graphicCard7.coreClock);
		System.out.println("this is graphicCard7 instance:boostClock " + graphicCard7.boostClock);
		System.out.println("this is graphicCard7 instance:cooling " + graphicCard7.cooling);
		System.out.println("this is graphicCard7 instance:powerConnector " + graphicCard7.powerConnector);
		System.out.println("this is graphicCard7 instance:tdp " + graphicCard7.tdp);
		System.out.println("this is graphicCard7 instance:compatibility " + graphicCard7.compatibility);

		graphicCard8.brand = "AMD";
		graphicCard8.vram = 8;
		graphicCard8.gpuChip = "RX6600";
		graphicCard8.busInterface = "PCIe4.0";
		graphicCard8.coreClock = 1626;
		graphicCard8.boostClock = 2491;
		graphicCard8.cooling = "DualFan";
		graphicCard8.powerConnector = "8Pin";
		graphicCard8.tdp = 132;
		graphicCard8.compatibility = "Mac";

		System.out.println("this is graphicCard8 instance:length " + graphicCard8.length);
		System.out.println("this is graphicCard8 instance:width " + graphicCard8.width);
		System.out.println("this is graphicCard8 instance:height " + graphicCard8.height);
		System.out.println("this is graphicCard8 instance:color " + graphicCard8.color);
		System.out.println("this is graphicCard8 instance:material " + graphicCard8.material);
		System.out.println("this is graphicCard8 instance:brand " + graphicCard8.brand);
		System.out.println("this is graphicCard8 instance:vram " + graphicCard8.vram);
		System.out.println("this is graphicCard8 instance:gpuChip " + graphicCard8.gpuChip);
		System.out.println("this is graphicCard8 instance:busInterface " + graphicCard8.busInterface);
		System.out.println("this is graphicCard8 instance:coreClock " + graphicCard8.coreClock);
		System.out.println("this is graphicCard8 instance:boostClock " + graphicCard8.boostClock);
		System.out.println("this is graphicCard8 instance:cooling " + graphicCard8.cooling);
		System.out.println("this is graphicCard8 instance:powerConnector " + graphicCard8.powerConnector);
		System.out.println("this is graphicCard8 instance:tdp " + graphicCard8.tdp);
		System.out.println("this is graphicCard8 instance:compatibility " + graphicCard8.compatibility);

		graphicCard9.brand = "Nvidia";
		graphicCard9.vram = 4;
		graphicCard9.gpuChip = "GTX1650";
		graphicCard9.busInterface = "PCIe3.0";
		graphicCard9.coreClock = 1485;
		graphicCard9.boostClock = 1665;
		graphicCard9.cooling = "SingleFan";
		graphicCard9.powerConnector = "6Pin";
		graphicCard9.tdp = 75;
		graphicCard9.compatibility = "Windows";

		System.out.println("this is graphicCard9 instance:length " + graphicCard9.length);
		System.out.println("this is graphicCard9 instance:width " + graphicCard9.width);
		System.out.println("this is graphicCard9 instance:height " + graphicCard9.height);
		System.out.println("this is graphicCard9 instance:color " + graphicCard9.color);
		System.out.println("this is graphicCard9 instance:material " + graphicCard9.material);
		System.out.println("this is graphicCard9 instance:brand " + graphicCard9.brand);
		System.out.println("this is graphicCard9 instance:vram " + graphicCard9.vram);
		System.out.println("this is graphicCard9 instance:gpuChip " + graphicCard9.gpuChip);
		System.out.println("this is graphicCard9 instance:busInterface " + graphicCard9.busInterface);
		System.out.println("this is graphicCard9 instance:coreClock " + graphicCard9.coreClock);
		System.out.println("this is graphicCard9 instance:boostClock " + graphicCard9.boostClock);
		System.out.println("this is graphicCard9 instance:cooling " + graphicCard9.cooling);
		System.out.println("this is graphicCard9 instance:powerConnector " + graphicCard9.powerConnector);
		System.out.println("this is graphicCard9 instance:tdp " + graphicCard9.tdp);
		System.out.println("this is graphicCard9 instance:compatibility " + graphicCard9.compatibility);

		graphicCard10.brand = "AMD";
		graphicCard10.vram = 32;
		graphicCard10.gpuChip = "RX7900XTX";
		graphicCard10.busInterface = "PCIe4.0";
		graphicCard10.coreClock = 1900;
		graphicCard10.boostClock = 2500;
		graphicCard10.cooling = "TripleFan";
		graphicCard10.powerConnector = "2x8Pin";
		graphicCard10.tdp = 355;
		graphicCard10.compatibility = "Linux";

		System.out.println("this is graphicCard10 instance:length " + graphicCard10.length);
		System.out.println("this is graphicCard10 instance:width " + graphicCard10.width);
		System.out.println("this is graphicCard10 instance:height " + graphicCard10.height);
		System.out.println("this is graphicCard10 instance:color " + graphicCard10.color);
		System.out.println("this is graphicCard10 instance:material " + graphicCard10.material);
		System.out.println("this is graphicCard10 instance:brand " + graphicCard10.brand);
		System.out.println("this is graphicCard10 instance:vram " + graphicCard10.vram);
		System.out.println("this is graphicCard10 instance:gpuChip " + graphicCard10.gpuChip);
		System.out.println("this is graphicCard10 instance:busInterface " + graphicCard10.busInterface);
		System.out.println("this is graphicCard10 instance:coreClock " + graphicCard10.coreClock);
		System.out.println("this is graphicCard10 instance:boostClock " + graphicCard10.boostClock);
		System.out.println("this is graphicCard10 instance:cooling " + graphicCard10.cooling);
		System.out.println("this is graphicCard10 instance:powerConnector " + graphicCard10.powerConnector);
		System.out.println("this is graphicCard10 instance:tdp " + graphicCard10.tdp);
		System.out.println("this is graphicCard10 instance:compatibility " + graphicCard10.compatibility);

		graphicCard6 = graphicCard7;
		System.out.println("this is graphicCard6 instance:length " + graphicCard6.length);
		System.out.println("this is graphicCard6 instance:width " + graphicCard6.width);
		System.out.println("this is graphicCard6 instance:height " + graphicCard6.height);
		System.out.println("this is graphicCard6 instance:color " + graphicCard6.color);
		System.out.println("this is graphicCard6 instance:material " + graphicCard6.material);
		System.out.println("this is graphicCard6 instance:brand " + graphicCard6.brand);
		System.out.println("this is graphicCard6 instance:vram " + graphicCard6.vram);
		System.out.println("this is graphicCard6 instance:gpuChip " + graphicCard6.gpuChip);
		System.out.println("this is graphicCard6 instance:busInterface " + graphicCard6.busInterface);
		System.out.println("this is graphicCard6 instance:coreClock " + graphicCard6.coreClock);
		System.out.println("this is graphicCard6 instance:boostClock " + graphicCard6.boostClock);
		System.out.println("this is graphicCard6 instance:cooling " + graphicCard6.cooling);
		System.out.println("this is graphicCard6 instance:powerConnector " + graphicCard6.powerConnector);
		System.out.println("this is graphicCard6 instance:tdp " + graphicCard6.tdp);
		System.out.println("this is graphicCard6 instance:compatibility " + graphicCard6.compatibility);
	}
}