class MouseRunner{
	public static void main(String... values){
		Mouse mouse1 = new Mouse();
		Mouse mouse2 = new Mouse();
		Mouse mouse3 = new Mouse();
		Mouse mouse4 = new Mouse();
		Mouse mouse5 = new Mouse();
		Mouse mouse6 = new Mouse();
		Mouse mouse7 = new Mouse();
		Mouse mouse8 = new Mouse();
		Mouse mouse9 = new Mouse();
		Mouse mouse10 = new Mouse();

		mouse1.buttons = 3;
		mouse1.weight = 120;
		mouse1.connectivity = "Wired";
		mouse1.dpi = 800;
		mouse1.type = "Optical";
		mouse1.usageMode = "Office";
		mouse1.sensor = "LED";
		mouse1.shape = "Ergonomic";
		mouse1.compatibility = "Windows";

		System.out.println("this is mouse1 instance:length " + mouse1.length);
		System.out.println("this is mouse1 instance:width " + mouse1.width);
		System.out.println("this is mouse1 instance:height " + mouse1.height);
		System.out.println("this is mouse1 instance:buttons " + mouse1.buttons);
		System.out.println("this is mouse1 instance:weight " + mouse1.weight);
		System.out.println("this is mouse1 instance:brand " + mouse1.brand);
		System.out.println("this is mouse1 instance:color " + mouse1.color);
		System.out.println("this is mouse1 instance:connectivity " + mouse1.connectivity);
		System.out.println("this is mouse1 instance:dpi " + mouse1.dpi);
		System.out.println("this is mouse1 instance:type " + mouse1.type);
		System.out.println("this is mouse1 instance:usageMode " + mouse1.usageMode);
		System.out.println("this is mouse1 instance:sensor " + mouse1.sensor);
		System.out.println("this is mouse1 instance:material " + mouse1.material);
		System.out.println("this is mouse1 instance:shape " + mouse1.shape);
		System.out.println("this is mouse1 instance:compatibility " + mouse1.compatibility);

		mouse2.buttons = 5;
		mouse2.weight = 140;
		mouse2.connectivity = "Wireless";
		mouse2.dpi = 1200;
		mouse2.type = "Laser";
		mouse2.usageMode = "Gaming";
		mouse2.sensor = "Laser";
		mouse2.shape = "Ambidextrous";
		mouse2.compatibility = "Mac";

		System.out.println("this is mouse2 instance:length " + mouse2.length);
		System.out.println("this is mouse2 instance:width " + mouse2.width);
		System.out.println("this is mouse2 instance:height " + mouse2.height);
		System.out.println("this is mouse2 instance:buttons " + mouse2.buttons);
		System.out.println("this is mouse2 instance:weight " + mouse2.weight);
		System.out.println("this is mouse2 instance:brand " + mouse2.brand);
		System.out.println("this is mouse2 instance:color " + mouse2.color);
		System.out.println("this is mouse2 instance:connectivity " + mouse2.connectivity);
		System.out.println("this is mouse2 instance:dpi " + mouse2.dpi);
		System.out.println("this is mouse2 instance:type " + mouse2.type);
		System.out.println("this is mouse2 instance:usageMode " + mouse2.usageMode);
		System.out.println("this is mouse2 instance:sensor " + mouse2.sensor);
		System.out.println("this is mouse2 instance:material " + mouse2.material);
		System.out.println("this is mouse2 instance:shape " + mouse2.shape);
		System.out.println("this is mouse2 instance:compatibility " + mouse2.compatibility);

		mouse3.buttons = 4;
		mouse3.weight = 110;
		mouse3.connectivity = "Bluetooth";
		mouse3.dpi = 1000;
		mouse3.type = "Optical";
		mouse3.usageMode = "Office";
		mouse3.sensor = "LED";
		mouse3.shape = "Compact";
		mouse3.compatibility = "Linux";

		System.out.println("this is mouse3 instance:length " + mouse3.length);
		System.out.println("this is mouse3 instance:width " + mouse3.width);
		System.out.println("this is mouse3 instance:height " + mouse3.height);
		System.out.println("this is mouse3 instance:buttons " + mouse3.buttons);
		System.out.println("this is mouse3 instance:weight " + mouse3.weight);
		System.out.println("this is mouse3 instance:brand " + mouse3.brand);
		System.out.println("this is mouse3 instance:color " + mouse3.color);
		System.out.println("this is mouse3 instance:connectivity " + mouse3.connectivity);
		System.out.println("this is mouse3 instance:dpi " + mouse3.dpi);
		System.out.println("this is mouse3 instance:type " + mouse3.type);
		System.out.println("this is mouse3 instance:usageMode " + mouse3.usageMode);
		System.out.println("this is mouse3 instance:sensor " + mouse3.sensor);
		System.out.println("this is mouse3 instance:material " + mouse3.material);
		System.out.println("this is mouse3 instance:shape " + mouse3.shape);
		System.out.println("this is mouse3 instance:compatibility " + mouse3.compatibility);

		mouse4.buttons = 6;
		mouse4.weight = 160;
		mouse4.connectivity = "Wireless";
		mouse4.dpi = 2400;
		mouse4.type = "Laser";
		mouse4.usageMode = "Gaming";
		mouse4.sensor = "Laser";
		mouse4.shape = "Ergonomic";
		mouse4.compatibility = "Windows";

		System.out.println("this is mouse4 instance:length " + mouse4.length);
		System.out.println("this is mouse4 instance:width " + mouse4.width);
		System.out.println("this is mouse4 instance:height " + mouse4.height);
		System.out.println("this is mouse4 instance:buttons " + mouse4.buttons);
		System.out.println("this is mouse4 instance:weight " + mouse4.weight);
		System.out.println("this is mouse4 instance:brand " + mouse4.brand);
		System.out.println("this is mouse4 instance:color " + mouse4.color);
		System.out.println("this is mouse4 instance:connectivity " + mouse4.connectivity);
		System.out.println("this is mouse4 instance:dpi " + mouse4.dpi);
		System.out.println("this is mouse4 instance:type " + mouse4.type);
		System.out.println("this is mouse4 instance:usageMode " + mouse4.usageMode);
		System.out.println("this is mouse4 instance:sensor " + mouse4.sensor);
		System.out.println("this is mouse4 instance:material " + mouse4.material);
		System.out.println("this is mouse4 instance:shape " + mouse4.shape);
		System.out.println("this is mouse4 instance:compatibility " + mouse4.compatibility);

		mouse5.buttons = 2;
		mouse5.weight = 90;
		mouse5.connectivity = "Wired";
		mouse5.dpi = 600;
		mouse5.type = "Optical";
		mouse5.usageMode = "Basic";
		mouse5.sensor = "LED";
		mouse5.shape = "Mini";
		mouse5.compatibility = "Windows";

		System.out.println("this is mouse5 instance:length " + mouse5.length);
		System.out.println("this is mouse5 instance:width " + mouse5.width);
		System.out.println("this is mouse5 instance:height " + mouse5.height);
		System.out.println("this is mouse5 instance:buttons " + mouse5.buttons);
		System.out.println("this is mouse5 instance:weight " + mouse5.weight);
		System.out.println("this is mouse5 instance:brand " + mouse5.brand);
		System.out.println("this is mouse5 instance:color " + mouse5.color);
		System.out.println("this is mouse5 instance:connectivity " + mouse5.connectivity);
		System.out.println("this is mouse5 instance:dpi " + mouse5.dpi);
		System.out.println("this is mouse5 instance:type " + mouse5.type);
		System.out.println("this is mouse5 instance:usageMode " + mouse5.usageMode);
		System.out.println("this is mouse5 instance:sensor " + mouse5.sensor);
		System.out.println("this is mouse5 instance:material " + mouse5.material);
		System.out.println("this is mouse5 instance:shape " + mouse5.shape);
		System.out.println("this is mouse5 instance:compatibility " + mouse5.compatibility);

		mouse6.buttons = 7;
		mouse6.weight = 175;
		mouse6.connectivity = "Wireless";
		mouse6.dpi = 3200;
		mouse6.type = "Optical";
		mouse6.usageMode = "Gaming";
		mouse6.sensor = "Infrared";
		mouse6.shape = "Ergonomic";
		mouse6.compatibility = "Windows";

		System.out.println("this is mouse6 instance:length " + mouse6.length);
		System.out.println("this is mouse6 instance:width " + mouse6.width);
		System.out.println("this is mouse6 instance:height " + mouse6.height);
		System.out.println("this is mouse6 instance:buttons " + mouse6.buttons);
		System.out.println("this is mouse6 instance:weight " + mouse6.weight);
		System.out.println("this is mouse6 instance:brand " + mouse6.brand);
		System.out.println("this is mouse6 instance:color " + mouse6.color);
		System.out.println("this is mouse6 instance:connectivity " + mouse6.connectivity);
		System.out.println("this is mouse6 instance:dpi " + mouse6.dpi);
		System.out.println("this is mouse6 instance:type " + mouse6.type);
		System.out.println("this is mouse6 instance:usageMode " + mouse6.usageMode);
		System.out.println("this is mouse6 instance:sensor " + mouse6.sensor);
		System.out.println("this is mouse6 instance:material " + mouse6.material);
		System.out.println("this is mouse6 instance:shape " + mouse6.shape);
		System.out.println("this is mouse6 instance:compatibility " + mouse6.compatibility);

		mouse7.buttons = 3;
		mouse7.weight = 100;
		mouse7.connectivity = "Bluetooth";
		mouse7.dpi = 1600;
		mouse7.type = "Optical";
		mouse7.usageMode = "Office";
		mouse7.sensor = "LED";
		mouse7.shape = "Compact";
		mouse7.compatibility = "Mac";

		System.out.println("this is mouse7 instance:length " + mouse7.length);
		System.out.println("this is mouse7 instance:width " + mouse7.width);
		System.out.println("this is mouse7 instance:height " + mouse7.height);
		System.out.println("this is mouse7 instance:buttons " + mouse7.buttons);
		System.out.println("this is mouse7 instance:weight " + mouse7.weight);
		System.out.println("this is mouse7 instance:brand " + mouse7.brand);
		System.out.println("this is mouse7 instance:color " + mouse7.color);
		System.out.println("this is mouse7 instance:connectivity " + mouse7.connectivity);
		System.out.println("this is mouse7 instance:dpi " + mouse7.dpi);
		System.out.println("this is mouse7 instance:type " + mouse7.type);
		System.out.println("this is mouse7 instance:usageMode " + mouse7.usageMode);
		System.out.println("this is mouse7 instance:sensor " + mouse7.sensor);
		System.out.println("this is mouse7 instance:material " + mouse7.material);
		System.out.println("this is mouse7 instance:shape " + mouse7.shape);
		System.out.println("this is mouse7 instance:compatibility " + mouse7.compatibility);

		mouse8.buttons = 8;
		mouse8.weight = 200;
		mouse8.connectivity = "Wired";
		mouse8.dpi = 4800;
		mouse8.type = "Laser";
		mouse8.usageMode = "Gaming";
		mouse8.sensor = "Laser";
		mouse8.shape = "Ergonomic";
		mouse8.compatibility = "Windows";

		System.out.println("this is mouse8 instance:length " + mouse8.length);
		System.out.println("this is mouse8 instance:width " + mouse8.width);
		System.out.println("this is mouse8 instance:height " + mouse8.height);
		System.out.println("this is mouse8 instance:buttons " + mouse8.buttons);
		System.out.println("this is mouse8 instance:weight " + mouse8.weight);
		System.out.println("this is mouse8 instance:brand " + mouse8.brand);
		System.out.println("this is mouse8 instance:color " + mouse8.color);
		System.out.println("this is mouse8 instance:connectivity " + mouse8.connectivity);
		System.out.println("this is mouse8 instance:dpi " + mouse8.dpi);
		System.out.println("this is mouse8 instance:type " + mouse8.type);
		System.out.println("this is mouse8 instance:usageMode " + mouse8.usageMode);
		System.out.println("this is mouse8 instance:sensor " + mouse8.sensor);
		System.out.println("this is mouse8 instance:material " + mouse8.material);
		System.out.println("this is mouse8 instance:shape " + mouse8.shape);
		System.out.println("this is mouse8 instance:compatibility " + mouse8.compatibility);

		mouse9.buttons = 4;
		mouse9.weight = 130;
		mouse9.connectivity = "Bluetooth";
		mouse9.dpi = 2000;
		mouse9.type = "Optical";
		mouse9.usageMode = "Office";
		mouse9.sensor = "Infrared";
		mouse9.shape = "Ambidextrous";
		mouse9.compatibility = "Linux";

		System.out.println("this is mouse9 instance:length " + mouse9.length);
		System.out.println("this is mouse9 instance:width " + mouse9.width);
		System.out.println("this is mouse9 instance:height " + mouse9.height);
		System.out.println("this is mouse9 instance:buttons " + mouse9.buttons);
		System.out.println("this is mouse9 instance:weight " + mouse9.weight);
		System.out.println("this is mouse9 instance:brand " + mouse9.brand);
		System.out.println("this is mouse9 instance:color " + mouse9.color);
		System.out.println("this is mouse9 instance:connectivity " + mouse9.connectivity);
		System.out.println("this is mouse9 instance:dpi " + mouse9.dpi);
		System.out.println("this is mouse9 instance:type " + mouse9.type);
		System.out.println("this is mouse9 instance:usageMode " + mouse9.usageMode);
		System.out.println("this is mouse9 instance:sensor " + mouse9.sensor);
		System.out.println("this is mouse9 instance:material " + mouse9.material);
		System.out.println("this is mouse9 instance:shape " + mouse9.shape);
		System.out.println("this is mouse9 instance:compatibility " + mouse9.compatibility);

		mouse10.buttons = 5;
		mouse10.weight = 150;
		mouse10.connectivity = "Wireless";
		mouse10.dpi = 2800;
		mouse10.type = "Laser";
		mouse10.usageMode = "Basic";
		mouse10.sensor = "LED";
		mouse10.shape = "Mini";
		mouse10.compatibility = "Mac";

		System.out.println("this is mouse10 instance:length " + mouse10.length);
		System.out.println("this is mouse10 instance:width " + mouse10.width);
		System.out.println("this is mouse10 instance:height " + mouse10.height);
		System.out.println("this is mouse10 instance:buttons " + mouse10.buttons);
		System.out.println("this is mouse10 instance:weight " + mouse10.weight);
		System.out.println("this is mouse10 instance:brand " + mouse10.brand);
		System.out.println("this is mouse10 instance:color " + mouse10.color);
		System.out.println("this is mouse10 instance:connectivity " + mouse10.connectivity);
		System.out.println("this is mouse10 instance:dpi " + mouse10.dpi);
		System.out.println("this is mouse10 instance:type " + mouse10.type);
		System.out.println("this is mouse10 instance:usageMode " + mouse10.usageMode);
		System.out.println("this is mouse10 instance:sensor " + mouse10.sensor);
		System.out.println("this is mouse10 instance:material " + mouse10.material);
		System.out.println("this is mouse10 instance:shape " + mouse10.shape);
		System.out.println("this is mouse10 instance:compatibility " + mouse10.compatibility);

		mouse6 = mouse7;
		System.out.println("this is mouse6 instance:length " + mouse6.length);
		System.out.println("this is mouse6 instance:width " + mouse6.width);
		System.out.println("this is mouse6 instance:height " + mouse6.height);
		System.out.println("this is mouse6 instance:buttons " + mouse6.buttons);
		System.out.println("this is mouse6 instance:weight " + mouse6.weight);
		System.out.println("this is mouse6 instance:brand " + mouse6.brand);
		System.out.println("this is mouse6 instance:color " + mouse6.color);
		System.out.println("this is mouse6 instance:connectivity " + mouse6.connectivity);
		System.out.println("this is mouse6 instance:dpi " + mouse6.dpi);
		System.out.println("this is mouse6 instance:type " + mouse6.type);
		System.out.println("this is mouse6 instance:usageMode " + mouse6.usageMode);
		System.out.println("this is mouse6 instance:sensor " + mouse6.sensor);
		System.out.println("this is mouse6 instance:material " + mouse6.material);
		System.out.println("this is mouse6 instance:shape " + mouse6.shape);
		System.out.println("this is mouse6 instance:compatibility " + mouse6.compatibility);
	}
}