class RouterRunner {
	public static void main(String... values) {
		Router router1 = new Router();
		Router router2 = new Router();
		Router router3 = new Router();
		Router router4 = new Router();
		Router router5 = new Router();
		Router router6 = new Router();
		Router router7 = new Router();
		Router router8 = new Router();
		Router router9 = new Router();
		Router router10 = new Router();

		router1.brand = "TP-Link";
		router1.model = "ArcherAX6000";
		router1.speedMbps = 6000;
		router1.wifiStandard = "WiFi6";
		router1.band = "DualBand";
		router1.antennas = 8;
		router1.security = "WPA3";
		router1.ports = "4xGigabit";
		router1.connectivity = "Wireless";
		router1.compatibility = "Windows";

		System.out.println("this is router1 instance:length " + router1.length);
		System.out.println("this is router1 instance:width " + router1.width);
		System.out.println("this is router1 instance:height " + router1.height);
		System.out.println("this is router1 instance:color " + router1.color);
		System.out.println("this is router1 instance:material " + router1.material);
		System.out.println("this is router1 instance:brand " + router1.brand);
		System.out.println("this is router1 instance:model " + router1.model);
		System.out.println("this is router1 instance:speedMbps " + router1.speedMbps);
		System.out.println("this is router1 instance:wifiStandard " + router1.wifiStandard);
		System.out.println("this is router1 instance:band " + router1.band);
		System.out.println("this is router1 instance:antennas " + router1.antennas);
		System.out.println("this is router1 instance:security " + router1.security);
		System.out.println("this is router1 instance:ports " + router1.ports);
		System.out.println("this is router1 instance:connectivity " + router1.connectivity);
		System.out.println("this is router1 instance:compatibility " + router1.compatibility);

		router2.brand = "Netgear";
		router2.model = "NighthawkAX12";
		router2.speedMbps = 10800;
		router2.wifiStandard = "WiFi6";
		router2.band = "TriBand";
		router2.antennas = 12;
		router2.security = "WPA3";
		router2.ports = "5xGigabit";
		router2.connectivity = "Wireless";
		router2.compatibility = "Mac";

		System.out.println("this is router2 instance:length " + router2.length);
		System.out.println("this is router2 instance:width " + router2.width);
		System.out.println("this is router2 instance:height " + router2.height);
		System.out.println("this is router2 instance:color " + router2.color);
		System.out.println("this is router2 instance:material " + router2.material);
		System.out.println("this is router2 instance:brand " + router2.brand);
		System.out.println("this is router2 instance:model " + router2.model);
		System.out.println("this is router2 instance:speedMbps " + router2.speedMbps);
		System.out.println("this is router2 instance:wifiStandard " + router2.wifiStandard);
		System.out.println("this is router2 instance:band " + router2.band);
		System.out.println("this is router2 instance:antennas " + router2.antennas);
		System.out.println("this is router2 instance:security " + router2.security);
		System.out.println("this is router2 instance:ports " + router2.ports);
		System.out.println("this is router2 instance:connectivity " + router2.connectivity);
		System.out.println("this is router2 instance:compatibility " + router2.compatibility);

		router3.brand = "Asus";
		router3.model = "RT-AX88U";
		router3.speedMbps = 6000;
		router3.wifiStandard = "WiFi6";
		router3.band = "DualBand";
		router3.antennas = 4;
		router3.security = "WPA2";
		router3.ports = "8xGigabit";
		router3.connectivity = "Wireless";
		router3.compatibility = "Linux";

		System.out.println("this is router3 instance:length " + router3.length);
		System.out.println("this is router3 instance:width " + router3.width);
		System.out.println("this is router3 instance:height " + router3.height);
		System.out.println("this is router3 instance:color " + router3.color);
		System.out.println("this is router3 instance:material " + router3.material);
		System.out.println("this is router3 instance:brand " + router3.brand);
		System.out.println("this is router3 instance:model " + router3.model);
		System.out.println("this is router3 instance:speedMbps " + router3.speedMbps);
		System.out.println("this is router3 instance:wifiStandard " + router3.wifiStandard);
		System.out.println("this is router3 instance:band " + router3.band);
		System.out.println("this is router3 instance:antennas " + router3.antennas);
		System.out.println("this is router3 instance:security " + router3.security);
		System.out.println("this is router3 instance:ports " + router3.ports);
		System.out.println("this is router3 instance:connectivity " + router3.connectivity);
		System.out.println("this is router3 instance:compatibility " + router3.compatibility);

		router4.brand = "Linksys";
		router4.model = "MR9600";
		router4.speedMbps = 9600;
		router4.wifiStandard = "WiFi6";
		router4.band = "DualBand";
		router4.antennas = 8;
		router4.security = "WPA3";
		router4.ports = "4xGigabit";
		router4.connectivity = "Wireless";
		router4.compatibility = "Windows";

		System.out.println("this is router4 instance:length " + router4.length);
		System.out.println("this is router4 instance:width " + router4.width);
		System.out.println("this is router4 instance:height " + router4.height);
		System.out.println("this is router4 instance:color " + router4.color);
		System.out.println("this is router4 instance:material " + router4.material);
		System.out.println("this is router4 instance:brand " + router4.brand);
		System.out.println("this is router4 instance:model " + router4.model);
		System.out.println("this is router4 instance:speedMbps " + router4.speedMbps);
		System.out.println("this is router4 instance:wifiStandard " + router4.wifiStandard);
		System.out.println("this is router4 instance:band " + router4.band);
		System.out.println("this is router4 instance:antennas " + router4.antennas);
		System.out.println("this is router4 instance:security " + router4.security);
		System.out.println("this is router4 instance:ports " + router4.ports);
		System.out.println("this is router4 instance:connectivity " + router4.connectivity);
		System.out.println("this is router4 instance:compatibility " + router4.compatibility);

		router5.brand = "DLink";
		router5.model = "DIR878";
		router5.speedMbps = 1900;
		router5.wifiStandard = "WiFi5";
		router5.band = "DualBand";
		router5.antennas = 4;
		router5.security = "WPA2";
		router5.ports = "4xGigabit";
		router5.connectivity = "Wireless";
		router5.compatibility = "Windows";

		System.out.println("this is router5 instance:length " + router5.length);
		System.out.println("this is router5 instance:width " + router5.width);
		System.out.println("this is router5 instance:height " + router5.height);
		System.out.println("this is router5 instance:color " + router5.color);
		System.out.println("this is router5 instance:material " + router5.material);
		System.out.println("this is router5 instance:brand " + router5.brand);
		System.out.println("this is router5 instance:model " + router5.model);
		System.out.println("this is router5 instance:speedMbps " + router5.speedMbps);
		System.out.println("this is router5 instance:wifiStandard " + router5.wifiStandard);
		System.out.println("this is router5 instance:band " + router5.band);
		System.out.println("this is router5 instance:antennas " + router5.antennas);
		System.out.println("this is router5 instance:security " + router5.security);
		System.out.println("this is router5 instance:ports " + router5.ports);
		System.out.println("this is router5 instance:connectivity " + router5.connectivity);
		System.out.println("this is router5 instance:compatibility " + router5.compatibility);

		router6.brand = "Cisco";
		router6.model = "RV340";
		router6.speedMbps = 1000;
		router6.wifiStandard = "WiFi5";
		router6.band = "DualBand";
		router6.antennas = 2;
		router6.security = "WPA2";
		router6.ports = "4xGigabit";
		router6.connectivity = "Wired";
		router6.compatibility = "Linux";

		System.out.println("this is router6 instance:length " + router6.length);
		System.out.println("this is router6 instance:width " + router6.width);
		System.out.println("this is router6 instance:height " + router6.height);
		System.out.println("this is router6 instance:color " + router6.color);
		System.out.println("this is router6 instance:material " + router6.material);
		System.out.println("this is router6 instance:brand " + router6.brand);
		System.out.println("this is router6 instance:model " + router6.model);
		System.out.println("this is router6 instance:speedMbps " + router6.speedMbps);
		System.out.println("this is router6 instance:wifiStandard " + router6.wifiStandard);
		System.out.println("this is router6 instance:band " + router6.band);
		System.out.println("this is router6 instance:antennas " + router6.antennas);
		System.out.println("this is router6 instance:security " + router6.security);
		System.out.println("this is router6 instance:ports " + router6.ports);
		System.out.println("this is router6 instance:connectivity " + router6.connectivity);
		System.out.println("this is router6 instance:compatibility " + router6.compatibility);

		router7.brand = "Google";
		router7.model = "Nest";
		router7.speedMbps = 2200;
		router7.wifiStandard = "WiFi5";
		router7.band = "TriBand";
		router7.antennas = 4;
		router7.security = "WPA3";
		router7.ports = "2xGigabit";
		router7.connectivity = "Wireless";
		router7.compatibility = "Android";

		System.out.println("this is router7 instance:length " + router7.length);
		System.out.println("this is router7 instance:width " + router7.width);
		System.out.println("this is router7 instance:height " + router7.height);
		System.out.println("this is router7 instance:color " + router7.color);
		System.out.println("this is router7 instance:material " + router7.material);
		System.out.println("this is router7 instance:brand " + router7.brand);
		System.out.println("this is router7 instance:model " + router7.model);
		System.out.println("this is router7 instance:speedMbps " + router7.speedMbps);
		System.out.println("this is router7 instance:wifiStandard " + router7.wifiStandard);
		System.out.println("this is router7 instance:band " + router7.band);
		System.out.println("this is router7 instance:antennas " + router7.antennas);
		System.out.println("this is router7 instance:security " + router7.security);
		System.out.println("this is router7 instance:ports " + router7.ports);
		System.out.println("this is router7 instance:connectivity " + router7.connectivity);
		System.out.println("this is router7 instance:compatibility " + router7.compatibility);

		router8.brand = "Eero";
		router8.model = "Pro6";
		router8.speedMbps = 1000;
		router8.wifiStandard = "WiFi6";
		router8.band = "TriBand";
		router8.antennas = 2;
		router8.security = "WPA3";
		router8.ports = "2xGigabit";
		router8.connectivity = "Wireless";
		router8.compatibility = "iOS";

		System.out.println("this is router8 instance:length " + router8.length);
		System.out.println("this is router8 instance:width " + router8.width);
		System.out.println("this is router8 instance:height " + router8.height);
		System.out.println("this is router8 instance:color " + router8.color);
		System.out.println("this is router8 instance:material " + router8.material);
		System.out.println("this is router8 instance:brand " + router8.brand);
		System.out.println("this is router8 instance:model " + router8.model);
		System.out.println("this is router8 instance:speedMbps " + router8.speedMbps);
		System.out.println("this is router8 instance:wifiStandard " + router8.wifiStandard);
		System.out.println("this is router8 instance:band " + router8.band);
		System.out.println("this is router8 instance:antennas " + router8.antennas);
		System.out.println("this is router8 instance:security " + router8.security);
		System.out.println("this is router8 instance:ports " + router8.ports);
		System.out.println("this is router8 instance:connectivity " + router8.connectivity);
		System.out.println("this is router8 instance:compatibility " + router8.compatibility);

		router9.brand = "Ubiquiti";
		router9.model = "UnifiDreamMachine";
		router9.speedMbps = 3500;
		router9.wifiStandard = "WiFi5";
		router9.band = "DualBand";
		router9.antennas = 4;
		router9.security = "WPA2";
		router9.ports = "4xGigabit";
		router9.connectivity = "Wireless";
		router9.compatibility = "Linux";

		System.out.println("this is router9 instance:length " + router9.length);
		System.out.println("this is router9 instance:width " + router9.width);
		System.out.println("this is router9 instance:height " + router9.height);
		System.out.println("this is router9 instance:color " + router9.color);
		System.out.println("this is router9 instance:material " + router9.material);
		System.out.println("this is router9 instance:brand " + router9.brand);
		System.out.println("this is router9 instance:model " + router9.model);
		System.out.println("this is router9 instance:speedMbps " + router9.speedMbps);
		System.out.println("this is router9 instance:wifiStandard " + router9.wifiStandard);
		System.out.println("this is router9 instance:band " + router9.band);
		System.out.println("this is router9 instance:antennas " + router9.antennas);
		System.out.println("this is router9 instance:security " + router9.security);
		System.out.println("this is router9 instance:ports " + router9.ports);
		System.out.println("this is router9 instance:connectivity " + router9.connectivity);
		System.out.println("this is router9 instance:compatibility " + router9.compatibility);

		router10.brand = "Asus";
		router10.model = "ZenWifiPro";
		router10.speedMbps = 7800;
		router10.wifiStandard = "WiFi6E";
		router10.band = "TriBand";
		router10.antennas = 6;
		router10.security = "WPA3";
		router10.ports = "4xGigabit";
		router10.connectivity = "Wireless";
		router10.compatibility = "Windows";

		System.out.println("this is router10 instance:length " + router10.length);
		System.out.println("this is router10 instance:width " + router10.width);
		System.out.println("this is router10 instance:height " + router10.height);
		System.out.println("this is router10 instance:color " + router10.color);
		System.out.println("this is router10 instance:material " + router10.material);
		System.out.println("this is router10 instance:brand " + router10.brand);
		System.out.println("this is router10 instance:model " + router10.model);
		System.out.println("this is router10 instance:speedMbps " + router10.speedMbps);
		System.out.println("this is router10 instance:wifiStandard " + router10.wifiStandard);
		System.out.println("this is router10 instance:band " + router10.band);
		System.out.println("this is router10 instance:antennas " + router10.antennas);
		System.out.println("this is router10 instance:security " + router10.security);
		System.out.println("this is router10 instance:ports " + router10.ports);
		System.out.println("this is router10 instance:connectivity " + router10.connectivity);
		System.out.println("this is router10 instance:compatibility " + router10.compatibility);

		router6 = router7;
		System.out.println("this is router6 instance:length " + router6.length);
		System.out.println("this is router6 instance:width " + router6.width);
		System.out.println("this is router6 instance:height " + router6.height);
		System.out.println("this is router6 instance:color " + router6.color);
		System.out.println("this is router6 instance:material " + router6.material);
		System.out.println("this is router6 instance:brand " + router6.brand);
		System.out.println("this is router6 instance:model " + router6.model);
		System.out.println("this is router6 instance:speedMbps " + router6.speedMbps);
		System.out.println("this is router6 instance:wifiStandard " + router6.wifiStandard);
		System.out.println("this is router6 instance:band " + router6.band);
		System.out.println("this is router6 instance:antennas " + router6.antennas);
		System.out.println("this is router6 instance:security " + router6.security);
		System.out.println("this is router6 instance:ports " + router6.ports);
		System.out.println("this is router6 instance:connectivity " + router6.connectivity);
		System.out.println("this is router6 instance:compatibility " + router6.compatibility);
	}
}