class SatelliteRunner {
	public static void main(String... values) {
		Satellite satellite1 = new Satellite();
		Satellite satellite2 = new Satellite();
		Satellite satellite3 = new Satellite();
		Satellite satellite4 = new Satellite();
		Satellite satellite5 = new Satellite();
		Satellite satellite6 = new Satellite();
		Satellite satellite7 = new Satellite();
		Satellite satellite8 = new Satellite();
		Satellite satellite9 = new Satellite();
		Satellite satellite10 = new Satellite();

		satellite1.name = "Hubble";
		satellite1.type = "Telescope";
		satellite1.orbit = "LEO";
		satellite1.altitude = 547.0;
		satellite1.purpose = "Astronomy";
		satellite1.launchVehicle = "SpaceShuttle";
		satellite1.operator = "NASA";
		satellite1.lifespan = 30;
		satellite1.powerSource = "SolarPanel";
		satellite1.status = "Active";

		System.out.println("this is satellite1 instance:length " + satellite1.length);
		System.out.println("this is satellite1 instance:width " + satellite1.width);
		System.out.println("this is satellite1 instance:height " + satellite1.height);
		System.out.println("this is satellite1 instance:color " + satellite1.color);
		System.out.println("this is satellite1 instance:material " + satellite1.material);
		System.out.println("this is satellite1 instance:name " + satellite1.name);
		System.out.println("this is satellite1 instance:type " + satellite1.type);
		System.out.println("this is satellite1 instance:orbit " + satellite1.orbit);
		System.out.println("this is satellite1 instance:altitude " + satellite1.altitude);
		System.out.println("this is satellite1 instance:purpose " + satellite1.purpose);
		System.out.println("this is satellite1 instance:launchVehicle " + satellite1.launchVehicle);
		System.out.println("this is satellite1 instance:operator " + satellite1.operator);
		System.out.println("this is satellite1 instance:lifespan " + satellite1.lifespan);
		System.out.println("this is satellite1 instance:powerSource " + satellite1.powerSource);
		System.out.println("this is satellite1 instance:status " + satellite1.status);

		satellite2.name = "GPS-IIF";
		satellite2.type = "Navigation";
		satellite2.orbit = "MEO";
		satellite2.altitude = 20200.0;
		satellite2.purpose = "Navigation";
		satellite2.launchVehicle = "DeltaIV";
		satellite2.operator = "USAF";
		satellite2.lifespan = 12;
		satellite2.powerSource = "SolarPanel";
		satellite2.status = "Active";

		System.out.println("this is satellite2 instance:length " + satellite2.length);
		System.out.println("this is satellite2 instance:width " + satellite2.width);
		System.out.println("this is satellite2 instance:height " + satellite2.height);
		System.out.println("this is satellite2 instance:color " + satellite2.color);
		System.out.println("this is satellite2 instance:material " + satellite2.material);
		System.out.println("this is satellite2 instance:name " + satellite2.name);
		System.out.println("this is satellite2 instance:type " + satellite2.type);
		System.out.println("this is satellite2 instance:orbit " + satellite2.orbit);
		System.out.println("this is satellite2 instance:altitude " + satellite2.altitude);
		System.out.println("this is satellite2 instance:purpose " + satellite2.purpose);
		System.out.println("this is satellite2 instance:launchVehicle " + satellite2.launchVehicle);
		System.out.println("this is satellite2 instance:operator " + satellite2.operator);
		System.out.println("this is satellite2 instance:lifespan " + satellite2.lifespan);
		System.out.println("this is satellite2 instance:powerSource " + satellite2.powerSource);
		System.out.println("this is satellite2 instance:status " + satellite2.status);

		satellite3.name = "Intelsat901";
		satellite3.type = "Communication";
		satellite3.orbit = "GEO";
		satellite3.altitude = 35786.0;
		satellite3.purpose = "Telecom";
		satellite3.launchVehicle = "ArianV";
		satellite3.operator = "Intelsat";
		satellite3.lifespan = 20;
		satellite3.powerSource = "SolarPanel";
		satellite3.status = "Retired";

		System.out.println("this is satellite3 instance:length " + satellite3.length);
		System.out.println("this is satellite3 instance:width " + satellite3.width);
		System.out.println("this is satellite3 instance:height " + satellite3.height);
		System.out.println("this is satellite3 instance:color " + satellite3.color);
		System.out.println("this is satellite3 instance:material " + satellite3.material);
		System.out.println("this is satellite3 instance:name " + satellite3.name);
		System.out.println("this is satellite3 instance:type " + satellite3.type);
		System.out.println("this is satellite3 instance:orbit " + satellite3.orbit);
		System.out.println("this is satellite3 instance:altitude " + satellite3.altitude);
		System.out.println("this is satellite3 instance:purpose " + satellite3.purpose);
		System.out.println("this is satellite3 instance:launchVehicle " + satellite3.launchVehicle);
		System.out.println("this is satellite3 instance:operator " + satellite3.operator);
		System.out.println("this is satellite3 instance:lifespan " + satellite3.lifespan);
		System.out.println("this is satellite3 instance:powerSource " + satellite3.powerSource);
		System.out.println("this is satellite3 instance:status " + satellite3.status);

		satellite4.name = "Landsat8";
		satellite4.type = "EarthObservation";
		satellite4.orbit = "LEO";
		satellite4.altitude = 705.0;
		satellite4.purpose = "Imaging";
		satellite4.launchVehicle = "AtlasV";
		satellite4.operator = "USGS";
		satellite4.lifespan = 10;
		satellite4.powerSource = "SolarPanel";
		satellite4.status = "Active";

		System.out.println("this is satellite4 instance:length " + satellite4.length);
		System.out.println("this is satellite4 instance:width " + satellite4.width);
		System.out.println("this is satellite4 instance:height " + satellite4.height);
		System.out.println("this is satellite4 instance:color " + satellite4.color);
		System.out.println("this is satellite4 instance:material " + satellite4.material);
		System.out.println("this is satellite4 instance:name " + satellite4.name);
		System.out.println("this is satellite4 instance:type " + satellite4.type);
		System.out.println("this is satellite4 instance:orbit " + satellite4.orbit);
		System.out.println("this is satellite4 instance:altitude " + satellite4.altitude);
		System.out.println("this is satellite4 instance:purpose " + satellite4.purpose);
		System.out.println("this is satellite4 instance:launchVehicle " + satellite4.launchVehicle);
		System.out.println("this is satellite4 instance:operator " + satellite4.operator);
		System.out.println("this is satellite4 instance:lifespan " + satellite4.lifespan);
		System.out.println("this is satellite4 instance:powerSource " + satellite4.powerSource);
		System.out.println("this is satellite4 instance:status " + satellite4.status);

		satellite5.name = "Starlink1";
		satellite5.type = "Communication";
		satellite5.orbit = "LEO";
		satellite5.altitude = 550.0;
		satellite5.purpose = "Internet";
		satellite5.launchVehicle = "Falcon9";
		satellite5.operator = "SpaceX";
		satellite5.lifespan = 5;
		satellite5.powerSource = "SolarPanel";
		satellite5.status = "Active";

		System.out.println("this is satellite5 instance:length " + satellite5.length);
		System.out.println("this is satellite5 instance:width " + satellite5.width);
		System.out.println("this is satellite5 instance:height " + satellite5.height);
		System.out.println("this is satellite5 instance:color " + satellite5.color);
		System.out.println("this is satellite5 instance:material " + satellite5.material);
		System.out.println("this is satellite5 instance:name " + satellite5.name);
		System.out.println("this is satellite5 instance:type " + satellite5.type);
		System.out.println("this is satellite5 instance:orbit " + satellite5.orbit);
		System.out.println("this is satellite5 instance:altitude " + satellite5.altitude);
		System.out.println("this is satellite5 instance:purpose " + satellite5.purpose);
		System.out.println("this is satellite5 instance:launchVehicle " + satellite5.launchVehicle);
		System.out.println("this is satellite5 instance:operator " + satellite5.operator);
		System.out.println("this is satellite5 instance:lifespan " + satellite5.lifespan);
		System.out.println("this is satellite5 instance:powerSource " + satellite5.powerSource);
		System.out.println("this is satellite5 instance:status " + satellite5.status);

		satellite6.name = "ISS";
		satellite6.type = "SpaceStation";
		satellite6.orbit = "LEO";
		satellite6.altitude = 408.0;
		satellite6.purpose = "Research";
		satellite6.launchVehicle = "Soyuz";
		satellite6.operator = "NASA";
		satellite6.lifespan = 30;
		satellite6.powerSource = "SolarPanel";
		satellite6.status = "Active";

		System.out.println("this is satellite6 instance:length " + satellite6.length);
		System.out.println("this is satellite6 instance:width " + satellite6.width);
		System.out.println("this is satellite6 instance:height " + satellite6.height);
		System.out.println("this is satellite6 instance:color " + satellite6.color);
		System.out.println("this is satellite6 instance:material " + satellite6.material);
		System.out.println("this is satellite6 instance:name " + satellite6.name);
		System.out.println("this is satellite6 instance:type " + satellite6.type);
		System.out.println("this is satellite6 instance:orbit " + satellite6.orbit);
		System.out.println("this is satellite6 instance:altitude " + satellite6.altitude);
		System.out.println("this is satellite6 instance:purpose " + satellite6.purpose);
		System.out.println("this is satellite6 instance:launchVehicle " + satellite6.launchVehicle);
		System.out.println("this is satellite6 instance:operator " + satellite6.operator);
		System.out.println("this is satellite6 instance:lifespan " + satellite6.lifespan);
		System.out.println("this is satellite6 instance:powerSource " + satellite6.powerSource);
		System.out.println("this is satellite6 instance:status " + satellite6.status);

		satellite7.name = "NOAA20";
		satellite7.type = "Weather";
		satellite7.orbit = "LEO";
		satellite7.altitude = 824.0;
		satellite7.purpose = "Meteorology";
		satellite7.launchVehicle = "DeltaII";
		satellite7.operator = "NOAA";
		satellite7.lifespan = 7;
		satellite7.powerSource = "SolarPanel";
		satellite7.status = "Active";

		System.out.println("this is satellite7 instance:length " + satellite7.length);
		System.out.println("this is satellite7 instance:width " + satellite7.width);
		System.out.println("this is satellite7 instance:height " + satellite7.height);
		System.out.println("this is satellite7 instance:color " + satellite7.color);
		System.out.println("this is satellite7 instance:material " + satellite7.material);
		System.out.println("this is satellite7 instance:name " + satellite7.name);
		System.out.println("this is satellite7 instance:type " + satellite7.type);
		System.out.println("this is satellite7 instance:orbit " + satellite7.orbit);
		System.out.println("this is satellite7 instance:altitude " + satellite7.altitude);
		System.out.println("this is satellite7 instance:purpose " + satellite7.purpose);
		System.out.println("this is satellite7 instance:launchVehicle " + satellite7.launchVehicle);
		System.out.println("this is satellite7 instance:operator " + satellite7.operator);
		System.out.println("this is satellite7 instance:lifespan " + satellite7.lifespan);
		System.out.println("this is satellite7 instance:powerSource " + satellite7.powerSource);
		System.out.println("this is satellite7 instance:status " + satellite7.status);

		satellite8.name = "Sputnik1";
		satellite8.type = "Experimental";
		satellite8.orbit = "LEO";
		satellite8.altitude = 577.0;
		satellite8.purpose = "Research";
		satellite8.launchVehicle = "R7";
		satellite8.operator = "USSR";
		satellite8.lifespan = 1;
		satellite8.powerSource = "Battery";
		satellite8.status = "Decommissioned";

		System.out.println("this is satellite8 instance:length " + satellite8.length);
		System.out.println("this is satellite8 instance:width " + satellite8.width);
		System.out.println("this is satellite8 instance:height " + satellite8.height);
		System.out.println("this is satellite8 instance:color " + satellite8.color);
		System.out.println("this is satellite8 instance:material " + satellite8.material);
		System.out.println("this is satellite8 instance:name " + satellite8.name);
		System.out.println("this is satellite8 instance:type " + satellite8.type);
		System.out.println("this is satellite8 instance:orbit " + satellite8.orbit);
		System.out.println("this is satellite8 instance:altitude " + satellite8.altitude);
		System.out.println("this is satellite8 instance:purpose " + satellite8.purpose);
		System.out.println("this is satellite8 instance:launchVehicle " + satellite8.launchVehicle);
		System.out.println("this is satellite8 instance:operator " + satellite8.operator);
		System.out.println("this is satellite8 instance:lifespan " + satellite8.lifespan);
		System.out.println("this is satellite8 instance:powerSource " + satellite8.powerSource);
		System.out.println("this is satellite8 instance:status " + satellite8.status);

		satellite9.name = "GSAT30";
		satellite9.type = "Communication";
		satellite9.orbit = "GEO";
		satellite9.altitude = 35786.0;
		satellite9.purpose = "Telecom";
		satellite9.launchVehicle = "ArianV";
		satellite9.operator = "ISRO";
		satellite9.lifespan = 15;
		satellite9.powerSource = "SolarPanel";
		satellite9.status = "Active";

		System.out.println("this is satellite9 instance:length " + satellite9.length);
		System.out.println("this is satellite9 instance:width " + satellite9.width);
		System.out.println("this is satellite9 instance:height " + satellite9.height);
		System.out.println("this is satellite9 instance:color " + satellite9.color);
		System.out.println("this is satellite9 instance:material " + satellite9.material);
		System.out.println("this is satellite9 instance:name " + satellite9.name);
		System.out.println("this is satellite9 instance:type " + satellite9.type);
		System.out.println("this is satellite9 instance:orbit " + satellite9.orbit);
		System.out.println("this is satellite9 instance:altitude " + satellite9.altitude);
		System.out.println("this is satellite9 instance:purpose " + satellite9.purpose);
		System.out.println("this is satellite9 instance:launchVehicle " + satellite9.launchVehicle);
		System.out.println("this is satellite9 instance:operator " + satellite9.operator);
		System.out.println("this is satellite9 instance:lifespan " + satellite9.lifespan);
		System.out.println("this is satellite9 instance:powerSource " + satellite9.powerSource);
		System.out.println("this is satellite9 instance:status " + satellite9.status);

		satellite10.name = "TerraSAR";
		satellite10.type = "EarthObservation";
		satellite10.orbit = "LEO";
		satellite10.altitude = 514.0;
		satellite10.purpose = "Radar";
		satellite10.launchVehicle = "Dnepr";
		satellite10.operator = "DLR";
		satellite10.lifespan = 10;
		satellite10.powerSource = "SolarPanel";
		satellite10.status = "Active";

		System.out.println("this is satellite10 instance:length " + satellite10.length);
		System.out.println("this is satellite10 instance:width " + satellite10.width);
		System.out.println("this is satellite10 instance:height " + satellite10.height);
		System.out.println("this is satellite10 instance:color " + satellite10.color);
		System.out.println("this is satellite10 instance:material " + satellite10.material);
		System.out.println("this is satellite10 instance:name " + satellite10.name);
		System.out.println("this is satellite10 instance:type " + satellite10.type);
		System.out.println("this is satellite10 instance:orbit " + satellite10.orbit);
		System.out.println("this is satellite10 instance:altitude " + satellite10.altitude);
		System.out.println("this is satellite10 instance:purpose " + satellite10.purpose);
		System.out.println("this is satellite10 instance:launchVehicle " + satellite10.launchVehicle);
		System.out.println("this is satellite10 instance:operator " + satellite10.operator);
		System.out.println("this is satellite10 instance:lifespan " + satellite10.lifespan);
		System.out.println("this is satellite10 instance:powerSource " + satellite10.powerSource);
		System.out.println("this is satellite10 instance:status " + satellite10.status);

		satellite6 = satellite7;
		System.out.println("this is satellite6 instance:length " + satellite6.length);
		System.out.println("this is satellite6 instance:width " + satellite6.width);
		System.out.println("this is satellite6 instance:height " + satellite6.height);
		System.out.println("this is satellite6 instance:color " + satellite6.color);
		System.out.println("this is satellite6 instance:material " + satellite6.material);
		System.out.println("this is satellite6 instance:name " + satellite6.name);
		System.out.println("this is satellite6 instance:type " + satellite6.type);
		System.out.println("this is satellite6 instance:orbit " + satellite6.orbit);
		System.out.println("this is satellite6 instance:altitude " + satellite6.altitude);
		System.out.println("this is satellite6 instance:purpose " + satellite6.purpose);
		System.out.println("this is satellite6 instance:launchVehicle " + satellite6.launchVehicle);
		System.out.println("this is satellite6 instance:operator " + satellite6.operator);
		System.out.println("this is satellite6 instance:lifespan " + satellite6.lifespan);
		System.out.println("this is satellite6 instance:powerSource " + satellite6.powerSource);
		System.out.println("this is satellite6 instance:status " + satellite6.status);
	}
}