class ZipRunner {
	public static void main(String... values) {
		Zip zip1 = new Zip();
		Zip zip2 = new Zip();
		Zip zip3 = new Zip();
		Zip zip4 = new Zip();
		Zip zip5 = new Zip();
		Zip zip6 = new Zip();
		Zip zip7 = new Zip();
		Zip zip8 = new Zip();
		Zip zip9 = new Zip();
		Zip zip10 = new Zip();

		zip1.brand = "YKK";
		zip1.type = "Coil";
		zip1.size = 5.0;
		zip1.teeth = "Nylon";
		zip1.pull = "Standard";
		zip1.finish = "Matte";
		zip1.application = "Jacket";
		zip1.lockType = "AutoLock";
		zip1.reversible = "No";
		zip1.standard = "ISO";

		System.out.println("this is zip1 instance:length " + zip1.length);
		System.out.println("this is zip1 instance:width " + zip1.width);
		System.out.println("this is zip1 instance:height " + zip1.height);
		System.out.println("this is zip1 instance:color " + zip1.color);
		System.out.println("this is zip1 instance:material " + zip1.material);
		System.out.println("this is zip1 instance:brand " + zip1.brand);
		System.out.println("this is zip1 instance:type " + zip1.type);
		System.out.println("this is zip1 instance:size " + zip1.size);
		System.out.println("this is zip1 instance:teeth " + zip1.teeth);
		System.out.println("this is zip1 instance:pull " + zip1.pull);
		System.out.println("this is zip1 instance:finish " + zip1.finish);
		System.out.println("this is zip1 instance:application " + zip1.application);
		System.out.println("this is zip1 instance:lockType " + zip1.lockType);
		System.out.println("this is zip1 instance:reversible " + zip1.reversible);
		System.out.println("this is zip1 instance:standard " + zip1.standard);

		zip2.brand = "YKK";
		zip2.type = "Metal";
		zip2.size = 8.0;
		zip2.teeth = "Brass";
		zip2.pull = "Decorative";
		zip2.finish = "Shiny";
		zip2.application = "Jeans";
		zip2.lockType = "PinLock";
		zip2.reversible = "No";
		zip2.standard = "ISO";

		System.out.println("this is zip2 instance:length " + zip2.length);
		System.out.println("this is zip2 instance:width " + zip2.width);
		System.out.println("this is zip2 instance:height " + zip2.height);
		System.out.println("this is zip2 instance:color " + zip2.color);
		System.out.println("this is zip2 instance:material " + zip2.material);
		System.out.println("this is zip2 instance:brand " + zip2.brand);
		System.out.println("this is zip2 instance:type " + zip2.type);
		System.out.println("this is zip2 instance:size " + zip2.size);
		System.out.println("this is zip2 instance:teeth " + zip2.teeth);
		System.out.println("this is zip2 instance:pull " + zip2.pull);
		System.out.println("this is zip2 instance:finish " + zip2.finish);
		System.out.println("this is zip2 instance:application " + zip2.application);
		System.out.println("this is zip2 instance:lockType " + zip2.lockType);
		System.out.println("this is zip2 instance:reversible " + zip2.reversible);
		System.out.println("this is zip2 instance:standard " + zip2.standard);

		zip3.brand = "Riri";
		zip3.type = "Invisible";
		zip3.size = 3.0;
		zip3.teeth = "Nylon";
		zip3.pull = "Hidden";
		zip3.finish = "Matte";
		zip3.application = "Dress";
		zip3.lockType = "NonLock";
		zip3.reversible = "No";
		zip3.standard = "ISO";

		System.out.println("this is zip3 instance:length " + zip3.length);
		System.out.println("this is zip3 instance:width " + zip3.width);
		System.out.println("this is zip3 instance:height " + zip3.height);
		System.out.println("this is zip3 instance:color " + zip3.color);
		System.out.println("this is zip3 instance:material " + zip3.material);
		System.out.println("this is zip3 instance:brand " + zip3.brand);
		System.out.println("this is zip3 instance:type " + zip3.type);
		System.out.println("this is zip3 instance:size " + zip3.size);
		System.out.println("this is zip3 instance:teeth " + zip3.teeth);
		System.out.println("this is zip3 instance:pull " + zip3.pull);
		System.out.println("this is zip3 instance:finish " + zip3.finish);
		System.out.println("this is zip3 instance:application " + zip3.application);
		System.out.println("this is zip3 instance:lockType " + zip3.lockType);
		System.out.println("this is zip3 instance:reversible " + zip3.reversible);
		System.out.println("this is zip3 instance:standard " + zip3.standard);

		zip4.brand = "SBS";
		zip4.type = "Waterproof";
		zip4.size = 10.0;
		zip4.teeth = "Plastic";
		zip4.pull = "Rubber";
		zip4.finish = "Matte";
		zip4.application = "Wetsuit";
		zip4.lockType = "AutoLock";
		zip4.reversible = "Yes";
		zip4.standard = "ISO";

		System.out.println("this is zip4 instance:length " + zip4.length);
		System.out.println("this is zip4 instance:width " + zip4.width);
		System.out.println("this is zip4 instance:height " + zip4.height);
		System.out.println("this is zip4 instance:color " + zip4.color);
		System.out.println("this is zip4 instance:material " + zip4.material);
		System.out.println("this is zip4 instance:brand " + zip4.brand);
		System.out.println("this is zip4 instance:type " + zip4.type);
		System.out.println("this is zip4 instance:size " + zip4.size);
		System.out.println("this is zip4 instance:teeth " + zip4.teeth);
		System.out.println("this is zip4 instance:pull " + zip4.pull);
		System.out.println("this is zip4 instance:finish " + zip4.finish);
		System.out.println("this is zip4 instance:application " + zip4.application);
		System.out.println("this is zip4 instance:lockType " + zip4.lockType);
		System.out.println("this is zip4 instance:reversible " + zip4.reversible);
		System.out.println("this is zip4 instance:standard " + zip4.standard);

		zip5.brand = "Coats";
		zip5.type = "Coil";
		zip5.size = 4.0;
		zip5.teeth = "Nylon";
		zip5.pull = "Standard";
		zip5.finish = "Matte";
		zip5.application = "Bag";
		zip5.lockType = "AutoLock";
		zip5.reversible = "No";
		zip5.standard = "ISO";

		System.out.println("this is zip5 instance:length " + zip5.length);
		System.out.println("this is zip5 instance:width " + zip5.width);
		System.out.println("this is zip5 instance:height " + zip5.height);
		System.out.println("this is zip5 instance:color " + zip5.color);
		System.out.println("this is zip5 instance:material " + zip5.material);
		System.out.println("this is zip5 instance:brand " + zip5.brand);
		System.out.println("this is zip5 instance:type " + zip5.type);
		System.out.println("this is zip5 instance:size " + zip5.size);
		System.out.println("this is zip5 instance:teeth " + zip5.teeth);
		System.out.println("this is zip5 instance:pull " + zip5.pull);
		System.out.println("this is zip5 instance:finish " + zip5.finish);
		System.out.println("this is zip5 instance:application " + zip5.application);
		System.out.println("this is zip5 instance:lockType " + zip5.lockType);
		System.out.println("this is zip5 instance:reversible " + zip5.reversible);
		System.out.println("this is zip5 instance:standard " + zip5.standard);

		zip6.brand = "YKK";
		zip6.type = "TwoWay";
		zip6.size = 5.0;
		zip6.teeth = "Nylon";
		zip6.pull = "Double";
		zip6.finish = "Shiny";
		zip6.application = "Jacket";
		zip6.lockType = "AutoLock";
		zip6.reversible = "Yes";
		zip6.standard = "ISO";

		System.out.println("this is zip6 instance:length " + zip6.length);
		System.out.println("this is zip6 instance:width " + zip6.width);
		System.out.println("this is zip6 instance:height " + zip6.height);
		System.out.println("this is zip6 instance:color " + zip6.color);
		System.out.println("this is zip6 instance:material " + zip6.material);
		System.out.println("this is zip6 instance:brand " + zip6.brand);
		System.out.println("this is zip6 instance:type " + zip6.type);
		System.out.println("this is zip6 instance:size " + zip6.size);
		System.out.println("this is zip6 instance:teeth " + zip6.teeth);
		System.out.println("this is zip6 instance:pull " + zip6.pull);
		System.out.println("this is zip6 instance:finish " + zip6.finish);
		System.out.println("this is zip6 instance:application " + zip6.application);
		System.out.println("this is zip6 instance:lockType " + zip6.lockType);
		System.out.println("this is zip6 instance:reversible " + zip6.reversible);
		System.out.println("this is zip6 instance:standard " + zip6.standard);

		zip7.brand = "Riri";
		zip7.type = "Metal";
		zip7.size = 6.0;
		zip7.teeth = "Aluminium";
		zip7.pull = "Decorative";
		zip7.finish = "Anodized";
		zip7.application = "Luggage";
		zip7.lockType = "PinLock";
		zip7.reversible = "No";
		zip7.standard = "ISO";

		System.out.println("this is zip7 instance:length " + zip7.length);
		System.out.println("this is zip7 instance:width " + zip7.width);
		System.out.println("this is zip7 instance:height " + zip7.height);
		System.out.println("this is zip7 instance:color " + zip7.color);
		System.out.println("this is zip7 instance:material " + zip7.material);
		System.out.println("this is zip7 instance:brand " + zip7.brand);
		System.out.println("this is zip7 instance:type " + zip7.type);
		System.out.println("this is zip7 instance:size " + zip7.size);
		System.out.println("this is zip7 instance:teeth " + zip7.teeth);
		System.out.println("this is zip7 instance:pull " + zip7.pull);
		System.out.println("this is zip7 instance:finish " + zip7.finish);
		System.out.println("this is zip7 instance:application " + zip7.application);
		System.out.println("this is zip7 instance:lockType " + zip7.lockType);
		System.out.println("this is zip7 instance:reversible " + zip7.reversible);
		System.out.println("this is zip7 instance:standard " + zip7.standard);

		zip8.brand = "SBS";
		zip8.type = "Coil";
		zip8.size = 3.0;
		zip8.teeth = "Polyester";
		zip8.pull = "Standard";
		zip8.finish = "Matte";
		zip8.application = "Tent";
		zip8.lockType = "NonLock";
		zip8.reversible = "No";
		zip8.standard = "ISO";

		System.out.println("this is zip8 instance:length " + zip8.length);
		System.out.println("this is zip8 instance:width " + zip8.width);
		System.out.println("this is zip8 instance:height " + zip8.height);
		System.out.println("this is zip8 instance:color " + zip8.color);
		System.out.println("this is zip8 instance:material " + zip8.material);
		System.out.println("this is zip8 instance:brand " + zip8.brand);
		System.out.println("this is zip8 instance:type " + zip8.type);
		System.out.println("this is zip8 instance:size " + zip8.size);
		System.out.println("this is zip8 instance:teeth " + zip8.teeth);
		System.out.println("this is zip8 instance:pull " + zip8.pull);
		System.out.println("this is zip8 instance:finish " + zip8.finish);
		System.out.println("this is zip8 instance:application " + zip8.application);
		System.out.println("this is zip8 instance:lockType " + zip8.lockType);
		System.out.println("this is zip8 instance:reversible " + zip8.reversible);
		System.out.println("this is zip8 instance:standard " + zip8.standard);

		zip9.brand = "Coats";
		zip9.type = "Metal";
		zip9.size = 5.0;
		zip9.teeth = "Zinc";
		zip9.pull = "Standard";
		zip9.finish = "Shiny";
		zip9.application = "Boots";
		zip9.lockType = "AutoLock";
		zip9.reversible = "No";
		zip9.standard = "ISO";

		System.out.println("this is zip9 instance:length " + zip9.length);
		System.out.println("this is zip9 instance:width " + zip9.width);
		System.out.println("this is zip9 instance:height " + zip9.height);
		System.out.println("this is zip9 instance:color " + zip9.color);
		System.out.println("this is zip9 instance:material " + zip9.material);
		System.out.println("this is zip9 instance:brand " + zip9.brand);
		System.out.println("this is zip9 instance:type " + zip9.type);
		System.out.println("this is zip9 instance:size " + zip9.size);
		System.out.println("this is zip9 instance:teeth " + zip9.teeth);
		System.out.println("this is zip9 instance:pull " + zip9.pull);
		System.out.println("this is zip9 instance:finish " + zip9.finish);
		System.out.println("this is zip9 instance:application " + zip9.application);
		System.out.println("this is zip9 instance:lockType " + zip9.lockType);
		System.out.println("this is zip9 instance:reversible " + zip9.reversible);
		System.out.println("this is zip9 instance:standard " + zip9.standard);

		zip10.brand = "YKK";
		zip10.type = "Waterproof";
		zip10.size = 8.0;
		zip10.teeth = "Plastic";
		zip10.pull = "Rubber";
		zip10.finish = "Matte";
		zip10.application = "Bag";
		zip10.lockType = "AutoLock";
		zip10.reversible = "Yes";
		zip10.standard = "ISO";

		System.out.println("this is zip10 instance:length " + zip10.length);
		System.out.println("this is zip10 instance:width " + zip10.width);
		System.out.println("this is zip10 instance:height " + zip10.height);
		System.out.println("this is zip10 instance:color " + zip10.color);
		System.out.println("this is zip10 instance:material " + zip10.material);
		System.out.println("this is zip10 instance:brand " + zip10.brand);
		System.out.println("this is zip10 instance:type " + zip10.type);
		System.out.println("this is zip10 instance:size " + zip10.size);
		System.out.println("this is zip10 instance:teeth " + zip10.teeth);
		System.out.println("this is zip10 instance:pull " + zip10.pull);
		System.out.println("this is zip10 instance:finish " + zip10.finish);
		System.out.println("this is zip10 instance:application " + zip10.application);
		System.out.println("this is zip10 instance:lockType " + zip10.lockType);
		System.out.println("this is zip10 instance:reversible " + zip10.reversible);
		System.out.println("this is zip10 instance:standard " + zip10.standard);

		zip6 = zip7;
		System.out.println("this is zip6 instance:length " + zip6.length);
		System.out.println("this is zip6 instance:width " + zip6.width);
		System.out.println("this is zip6 instance:height " + zip6.height);
		System.out.println("this is zip6 instance:color " + zip6.color);
		System.out.println("this is zip6 instance:material " + zip6.material);
		System.out.println("this is zip6 instance:brand " + zip6.brand);
		System.out.println("this is zip6 instance:type " + zip6.type);
		System.out.println("this is zip6 instance:size " + zip6.size);
		System.out.println("this is zip6 instance:teeth " + zip6.teeth);
		System.out.println("this is zip6 instance:pull " + zip6.pull);
		System.out.println("this is zip6 instance:finish " + zip6.finish);
		System.out.println("this is zip6 instance:application " + zip6.application);
		System.out.println("this is zip6 instance:lockType " + zip6.lockType);
		System.out.println("this is zip6 instance:reversible " + zip6.reversible);
		System.out.println("this is zip6 instance:standard " + zip6.standard);
	}
}